require 'rubygems'
require 'bundler/setup'
require 'pry'
require './lib/app_config'

require 'sqlite3'
require 'hashie/mash'
require 'active_record'
require 'yaml'

connection_details =  AppConfig.instance.config.database
ActiveRecord::Base.establish_connection(connection_details)

class Word < ActiveRecord::Base
end

words = words = [
  {word: "a", transcription: "[э]", translate: "определенный артикль, один из, неопределенный"},
  {word: "able", transcription: "[эйбл]", translate: "способный, могущий, умелый"},
  {word: "about", transcription: "[эбáут]", translate: "о, около, приблизительно"},
  {word: "above", transcription: "[эбáв]", translate: "над, выше, наверху"},
  {word: "accept", transcription: "[эксéпт]", translate: "принимать, соглашаться, одобрять"},
  {word: "across", transcription: "[экрóс]", translate: "через, поперек, напротив"},
  {word: "act", transcription: "[экт]", translate: "действовать, поступать, акт"},
  {word: "actually", transcription: "[áкчуэли]", translate: "фактически, в самом деле, на самом деле"},
  {word: "add", transcription: "[эд]", translate: "добавлять, прибавлять, сумма"},
  {word: "admit", transcription: "[эдмúт]", translate: "признавать, допускать, разрешать"},
  {word: "afraid", transcription: "[эфрéйд]", translate: "испуганный, боящийся, опасающийся"},
  {word: "after", transcription: "[áфтэр]", translate: "после, затем, потом"},
  {word: "afternoon", transcription: "[áфтэрнýн]", translate: "после полудня, день, вторая половина дня"},
  {word: "again", transcription: "[эгéн]", translate: "снова, опять, еще раз"},
  {word: "against", transcription: "[эгéнст]", translate: "против, напротив, вопреки"},
  {word: "age", transcription: "[эйдж]", translate: "возраст, век, эпоха"},
  {word: "ago", transcription: "[эгóу]", translate: "назад, давно, тому назад"},
  {word: "agree", transcription: "[эгрú]", translate: "соглашаться, согласен, одобрять"},
  {word: "ah", transcription: "[а]", translate: "ах, о, восклицание"},
  {word: "ahead", transcription: "[эхéд]", translate: "вперед, впереди, далее"},
  {word: "air", transcription: "[эр]", translate: "воздух, атмосфера, аэр"},
  {word: "all", transcription: "[ол]", translate: "все, весь, целиком"},
  {word: "allow", transcription: "[элáу]", translate: "позволять, разрешать, допускать"},
  {word: "almost", transcription: "[óлмоуст]", translate: "почти, приблизительно, едва не"},
  {word: "alone", transcription: "[элóун]", translate: "один, в одиночестве, единственный"},
  {word: "along", transcription: "[элóнг]", translate: "вдоль, по, согласно"},
  {word: "already", transcription: "[олрéди]", translate: "уже, теперь, сейчас"},
  {word: "alright", transcription: "[олрáйт]", translate: "хорошо, ладно, договорились"},
  {word: "also", transcription: "[óлсоу]", translate: "также, тоже, кроме того"},
  {word: "although", transcription: "[олзóу]", translate: "хотя, несмотря на то что, пусть"},
  {word: "always", transcription: "[óлвэйз]", translate: "всегда, постоянно, неизменно"},
  {word: "am", transcription: "[эм]", translate: "являюсь, есть, быть (1 л. ед. ч. наст. вр.)"},
  {word: "amaze", transcription: "[эмэ́йз]", translate: "удивлять, поражать, изумлять"},
  {word: "an", transcription: "[эн]", translate: "неопределенный артикль, один из"},
  {word: "and", transcription: "[энд]", translate: "и, а также, плюс"},
  {word: "anger", transcription: "[áнгэр]", translate: "гнев, злость, ярость"},
  {word: "angry", transcription: "[áнгри]", translate: "злой, сердитый, разгневанный"},
  {word: "animal", transcription: "[áнимэл]", translate: "животное, зверь, питомец"},
  {word: "annoy", transcription: "[энóй]", translate: "раздражать, досаждать, надоедать"},
  {word: "another", transcription: "[энáзэр]", translate: "другой, иной, альтернативный"},
  {word: "answer", transcription: "[áнсэр]", translate: "ответ, решение, отвечать"},
  {word: "any", transcription: "[éни]", translate: "любой, какой-либо, всякий"},
  {word: "anymore", transcription: "[энимóр]", translate: "больше не, более нет, уже нет"},
  {word: "anyone", transcription: "[éнивэн]", translate: "кто-то, кто-нибудь, любой человек"},
  {word: "anything", transcription: "[éнизинг]", translate: "что-то, что-нибудь, что угодно"},
  {word: "anyway", transcription: "[éнивэй]", translate: "в любом случае, как бы то ни было, все равно"},
  {word: "apartment", transcription: "[эпáртмэнт]", translate: "квартира, апартаменты, жилье"},
  {word: "apparently", transcription: "[эпáрэнтли]", translate: "очевидно, по-видимому, видимо"},
  {word: "appear", transcription: "[эпúр]", translate: "появляться, возникать, казаться"},
  {word: "approach", transcription: "[эпрóуч]", translate: "подходить, приближаться, метод"},
  {word: "are", transcription: "[ар]", translate: "быть, являться (форма глагола), существовать"},
  {word: "area", transcription: "[éриэ]", translate: "область, район, участок, зона"},
  {word: "aren't", transcription: "[арнт]", translate: "не быть (сокращенная форма), не являются"},
  {word: "arm", transcription: "[арм]", translate: "рука, плечо, конечность"},
  {word: "around", transcription: "[эрáунд]", translate: "вокруг, около, повсюду"},
  {word: "arrive", transcription: "[эрáйв]", translate: "прибывать, приезжать, достигать"},
  {word: "as", transcription: "[эз]", translate: "как, в качестве, поскольку"},
  {word: "ask", transcription: "[аск]", translate: "спрашивать, просить, требовать"},
  {word: "asleep", transcription: "[эслúп]", translate: "спящий, спит, во сне"},
  {word: "ass", transcription: "[эс]", translate: "жопа, задница, ослиная шкура"},
  {word: "at", transcription: "[эт]", translate: "у, в, на, по (указывает место)"},
  {word: "attack", transcription: "[этáк]", translate: "атаковать, нападать, атака"},
  {word: "attempt", transcription: "[этéмпт]", translate: "попытка, стараться, пытаться"},
  {word: "attention", transcription: "[этéншн]", translate: "внимание, забота, уважение"},
  {word: "aunt", transcription: "[ант]", translate: "тётя, тётушка, родственница"},
  {word: "avoid", transcription: "[эвóйд]", translate: "избегать, уклоняться, сторониться"},
  {word: "away", transcription: "[эвэ́й]", translate: "далеко, прочь, на расстоянии"},
  {word: "baby", transcription: "[бэ́йби]", translate: "младенец, ребенок, малыш"},
  {word: "back", transcription: "[бэк]", translate: "спина, назад, обратно, задний"},
  {word: "bad", transcription: "[бэд]", translate: "плохой, дурной, негодный"},
  {word: "bag", transcription: "[бэг]", translate: "сумка, мешок, пакет"},
  {word: "ball", transcription: "[бол]", translate: "мяч, шар, бал"},
  {word: "band", transcription: "[бэнд]", translate: "группа, банда, оркестр, лента"},
  {word: "bar", transcription: "[бар]", translate: "полоса, бар, преграда, стержень"},
  {word: "barely", transcription: "[бэ́рли]", translate: "едва ли, с трудом, чуть"},
  {word: "bathroom", transcription: "[бáсрум]", translate: "ванная комната, туалет, уборная"},
  {word: "be", transcription: "[би]", translate: "быть, являться (форма глагола), существовать"},
  {word: "beat", transcription: "[бит]", translate: "победить, ударить, бить, ритм"},
  {word: "beautiful", transcription: "[бьюти́фул]", translate: "красивый, прекрасный, восхитительный"},
  {word: "became", transcription: "[бикэ́йм]", translate: "стал, стала (прошедшее время от become), сделался"},
  {word: "because", transcription: "[бикóз]", translate: "потому что, так как, ибо"},
  {word: "become", transcription: "[бикáм]", translate: "становиться, делаться, обращаться"},
  {word: "bed", transcription: "[бед]", translate: "кровать, постель, ложе"},
  {word: "bedroom", transcription: "[бéдрум]", translate: "спальня, комната для сна"},
  {word: "been", transcription: "[бин]", translate: "был, была (прошедшее время от be), находился"},
  {word: "before", transcription: "[бифóр]", translate: "перед, до, прежде"},
  {word: "began", transcription: "[бигэ́н]", translate: "начал (прошедшее время от begin), начался"},
  {word: "begin", transcription: "[бигúн]", translate: "начинать, открывать, зачинать"},
  {word: "behind", transcription: "[бихáйнд]", translate: "позади, за, сзади, отставать"},
  {word: "believe", transcription: "[билú́в]", translate: "верить, доверять, полагать"},
  {word: "bell", transcription: "[бел]", translate: "колокол, звонок, бубенчик"},
  {word: "beside", transcription: "[бисáйд]", translate: "рядом, около, помимо"},
  {word: "besides", transcription: "[бисáйдз]", translate: "кроме, помимо, также, сверх того"},
  {word: "best", transcription: "[бест]", translate: "лучший, наилучший, превосходный"},
  {word: "better", transcription: "[бéтэр]", translate: "лучше, предпочтительнее, более"},
  {word: "between", transcription: "[битвúн]", translate: "между, посреди, среди"},
  {word: "big", transcription: "[биг]", translate: "большой, крупный, значительный"},
  {word: "bit", transcription: "[бит]", translate: "немного, чуть-чуть, кусочек"},
  {word: "bite", transcription: "[байт]", translate: "кусать, укус, захват"},
  {word: "black", transcription: "[блэк]", translate: "черный, темный, мрачный"},
  {word: "blink", transcription: "[блинк]", translate: "мигать, моргать, мерцать"},
  {word: "block", transcription: "[блок]", translate: "блокировать, преграждать, блок"},
  {word: "blonde", transcription: "[блонд]", translate: "блондин(ка), белокурый"},
  {word: "blood", transcription: "[блад]", translate: "кровь, родство, происхождение"},
  {word: "blue", transcription: "[блу]", translate: "синий, голубой, синева"},
  {word: "blush", transcription: "[блаш]", translate: "румянец, краснеть, багровый"},
  {word: "body", transcription: "[бóди]", translate: "тело, туловище, корпус"},
  {word: "book", transcription: "[бук]", translate: "книга, брошюра, заказывать"},
  {word: "bore", transcription: "[бор]", translate: "скучный, надоедливый, сверлить"},
  {word: "both", transcription: "[боус]", translate: "оба, обе, и тот и другой"},
  {word: "bother", transcription: "[бáзэр]", translate: "беспокоить, тревожить, затруднять"},
  {word: "bottle", transcription: "[бóтл]", translate: "бутылка, емкость, баллон"},
  {word: "bottom", transcription: "[бóтэм]", translate: "нижняя часть, низ, дно"},
  {word: "box", transcription: "[бокс]", translate: "коробка, ящик, бокс"},
  {word: "boy", transcription: "[бой]", translate: "мальчик, парень, юноша"},
  {word: "boyfriend", transcription: "[бóйфренд]", translate: "бойфренд, дружок, парень"},
  {word: "brain", transcription: "[брэйн]", translate: "мозг, интеллект, разум"},
  {word: "break", transcription: "[брэйк]", translate: "перерыв, ломать, нарушать"},
  {word: "breakfast", transcription: "[брéкфэст]", translate: "завтрак, утренняя еда"},
  {word: "breath", transcription: "[брэс]", translate: "дыхание, вздох, пар"},
  {word: "breathe", transcription: "[бриз]", translate: "дышать, вдыхать, выдыхать"},
  {word: "bright", transcription: "[брайт]", translate: "яркий, светлый, блестящий"},
  {word: "bring", transcription: "[бринг]", translate: "приносить, доставлять, вести"},
  {word: "broke", transcription: "[броук]", translate: "разбитый, сломанный (прошедшее время от break), банкрот"},
  {word: "broken", transcription: "[броукн]", translate: "разбитый, сломанный, поврежденный"},
  {word: "brother", transcription: "[брáзэр]", translate: "брат, собрат, единоверец"},
  {word: "brought", transcription: "[брот]", translate: "принес (прошедшее время от bring), доставил"},
  {word: "brown", transcription: "[браун]", translate: "коричневый, бурый, загорелый"},
  {word: "brush", transcription: "[браш]", translate: "щетка, чистить, красить"},
  {word: "build", transcription: "[билд]", translate: "строить, возводить, создавать"},
  {word: "burn", transcription: "[бёрн]", translate: "гореть, жечь, сжигать"},
  {word: "burst", transcription: "[бёрст]", translate: "взрыв, взрываться, прорываться"},
  {word: "bus", transcription: "[бас]", translate: "автобус, омнибус, маршрут"},
  {word: "business", transcription: "[бизнэс]", translate: "бизнес, дело, коммерция"},
  {word: "busy", transcription: "[бизи]", translate: "занятой, деловой, оживленный"},
  {word: "but", transcription: "[бат]", translate: "но, однако, зато"},
  {word: "buy", transcription: "[бай]", translate: "покупать, приобретать, закупать"},
  {word: "by", transcription: "[бай]", translate: "по, от, мимо, около"},
  {word: "call", transcription: "[кол]", translate: "звонить, называть, вызывать"},
  {word: "calm", transcription: "[кам]", translate: "спокойный, безмятежный, тихий"},
  {word: "came", transcription: "[кэйм]", translate: "пришел, пришла (прошедшее время от come), прибыл"},
  {word: "can", transcription: "[кэн]", translate: "мочь, уметь, быть в состоянии"},
  {word: "can't", transcription: "[кант]", translate: "не мочь, не уметь, не в состоянии"},
  {word: "car", transcription: "[кар]", translate: "машина, автомобиль, вагон"},
  {word: "card", transcription: "[кард]", translate: "карта, карточка, открытка"},
  {word: "care", transcription: "[кэр]", translate: "забота, ухаживать, беспокоиться"},
  {word: "carefully", transcription: "[кэрфули]", translate: "осторожно, бережно, внимательно"},
  {word: "carry", transcription: "[кэ́ри]", translate: "нести, переносить, доставлять"},
  {word: "case", transcription: "[кэйс]", translate: "случай, ситуация, ящик"},
  {word: "cat", transcription: "[кэт]", translate: "кот, кошка, котенок"},
  {word: "catch", transcription: "[кэч]", translate: "ловить, поймать, захватывать, догонять"},
  {word: "caught", transcription: "[кот]", translate: "пойманный, захваченный, схваченный"},
  {word: "cause", transcription: "[коз]", translate: "причина, вызывать, порождать, являться причиной"},
  {word: "cell", transcription: "[сел]", translate: "ячейка, клетка, элемент, камера"},
  {word: "chair", transcription: "[чэр]", translate: "стул, кресло, председатель"},
  {word: "chance", transcription: "[чанс]", translate: "шанс, случай, возможность, вероятность"},
  {word: "change", transcription: "[чэйндж]", translate: "изменение, менять, изменять, сдача"},
  {word: "chase", transcription: "[чэйс]", translate: "погоня, гнаться, преследовать, охота"},
  {word: "check", transcription: "[чек]", translate: "проверка, проверять, чек, контроль"},
  {word: "cheek", transcription: "[чик]", translate: "щека, наглость, дерзость"},
  {word: "chest", transcription: "[чест]", translate: "грудь, сундук, ящик, комод"},
  {word: "child", transcription: "[чайлд]", translate: "ребенок, дитя, детеныш"},
  {word: "children", transcription: "[чилдрэн]", translate: "дети, детишки, потомство"},
  {word: "chuckle", transcription: "[чакл]", translate: "хихикать, посмеиваться, хихиканье"},
  {word: "city", transcription: "[сити]", translate: "город, центр, мегаполис"},
  {word: "class", transcription: "[клас]", translate: "класс, курс, категория, ранг"},
  {word: "clean", transcription: "[клин]", translate: "чистый, убирать, вычищать, безупречный"},
  {word: "clear", transcription: "[клир]", translate: "чистый, ясный, четкий, прозрачный"},
  {word: "climb", transcription: "[клайм]", translate: "взбираться, подниматься, карабкаться"},
  {word: "close", transcription: "[клоуз]", translate: "близкий, закрывать, запирать, смыкать"},
  {word: "clothes", transcription: "[клоузз]", translate: "одежда, платье, наряд, костюм"},
  {word: "coffee", transcription: "[кофи]", translate: "кофе, кофейный напиток, кофейня"},
  {word: "cold", transcription: "[коулд]", translate: "холодный, холод, простуда, безучастный"},
  {word: "college", transcription: "[коллидж]", translate: "колледж, училище, университет, институт"},
  {word: "color", transcription: "[каллэр]", translate: "цвет, краска, расцветка, оттенок"},
  {word: "come", transcription: "[кам]", translate: "приходить, являться, прибывать, наступать"},
  {word: "comment", transcription: "[комментт]", translate: "комментарий, замечание, отзыв, высказывание"},
  {word: "complete", transcription: "[кэмплитт]", translate: "полный, завершать, заканчивать, исчерпывающий"},
  {word: "completely", transcription: "[кэмплиттли]", translate: "полностью, целиком, окончательно, всецело"},
  {word: "computer", transcription: "[кэмпьюттэр]", translate: "компьютер, вычислительная машина, ЭВМ"},
  {word: "concern", transcription: "[кэнсёрн]", translate: "беспокойство, касаться, волновать, относиться"},
  {word: "confuse", transcription: "[кэнфьюз]", translate: "путать, смущать, приводить в замешательство"},
  {word: "consider", transcription: "[кэнсидэр]", translate: "рассматривать, считать, полагать, принимать во внимание"},
  {word: "continue", transcription: "[кэнтинью]", translate: "продолжать, длиться, следовать, идти дальше"},
  {word: "control", transcription: "[кэнтроул]", translate: "контроль, управлять, регулировать, сдерживать"},
  {word: "conversation", transcription: "[конвэрсэйшн]", translate: "разговор, беседа, диалог, общение"},
  {word: "cool", transcription: "[кул]", translate: "прохладный, клевый, потрясающий, крутой"},
  {word: "corner", transcription: "[корнэр]", translate: "угол, закоулок, уголок, квартал"},
  {word: "couch", transcription: "[кауч]", translate: "диван, кушетка, софа, лежанка"},
  {word: "could", transcription: "[кудд]", translate: "мог, могли, был способен, имел возможность"},
  {word: "couldn't", transcription: "[куддэнт]", translate: "не мог, не могли, не был способен, не имел возможности"},
  {word: "counter", transcription: "[каунтэр]", translate: "прилавок, счетчик, противодействовать, отвечать"},
  {word: "couple", transcription: "[капл]", translate: "пара, несколько, чета, парочка"},
  {word: "course", transcription: "[корс]", translate: "курс, ход, путь, течение, процесс"},
  {word: "cover", transcription: "[ковэр]", translate: "покрытие, накрывать, обложка, крышка"},
  {word: "crack", transcription: "[крэк]", translate: "треск, трещина, разлом, щель"},
  {word: "crazy", transcription: "[крэйзи]", translate: "сумасшедший, безумный, чокнутый, ненормальный"},
  {word: "cross", transcription: "[кросс]", translate: "пересекать, переходить, крест, крестик"},
  {word: "crowd", transcription: "[крауд]", translate: "толпа, народ, множество, масса"},
  {word: "cry", transcription: "[край]", translate: "плакать, кричать, вопить, рыдать"},
  {word: "cup", transcription: "[кап]", translate: "чашка"},
  {word: "cut", transcription: "[кат]", translate: "резать"},
  {word: "cute", transcription: "[кьют]", translate: "милый, симпатичный"},
  {word: "dad", transcription: "[дэд]", translate: "папа"},
  {word: "damn", transcription: "[дэм]", translate: "проклятие, черт"},
  {word: "dance", transcription: "[данс]", translate: "танцевать"},
  {word: "dark", transcription: "[дарк]", translate: "темный"},
  {word: "date", transcription: "[дейт]", translate: "свидание"},
  {word: "daughter", transcription: "[дотэр]", translate: "дочь"},
  {word: "day", transcription: "[дей]", translate: "день"},
  {word: "dead", transcription: "[дэд]", translate: "мертвый"},
  {word: "deal", transcription: "[дил]", translate: "сделка, соглашение"},
  {word: "dear", transcription: "[дир]", translate: "дорогой, любимый"},
  {word: "death", transcription: "[дэс]", translate: "смерть"},
  {word: "decide", transcription: "[дисайд]", translate: "решить"},
  {word: "deep", transcription: "[дип]", translate: "глубокий"},
  {word: "definitely", transcription: "[дефинитли]", translate: "определенно"},
  {word: "desk", transcription: "[деск]", translate: "письменный стол, стол"},
  {word: "did", transcription: "[дид]", translate: "делал"},
  {word: "didn't", transcription: "[диднт]", translate: "не делал"},
  {word: "die", transcription: "[дай]", translate: "умирать"},
  {word: "different", transcription: "[дифэрэнт]", translate: "разный, различный"},
  {word: "dinner", transcription: "[диннэр]", translate: "ужин"},
  {word: "direction", transcription: "[дирекшн]", translate: "направление"},
  {word: "disappear", transcription: "[дисэпиэр]", translate: "исчезать"},
  {word: "do", transcription: "[ду]", translate: "делать"},
  {word: "doctor", transcription: "[доктэр]", translate: "врач"},
  {word: "does", transcription: "[даз]", translate: "делает"},
  {word: "doesn't", transcription: "[дазнт]", translate: "не делает"},
  {word: "dog", transcription: "[дог]", translate: "собака"},
  {word: "don't", transcription: "[доунт]", translate: "не делай, не делать"},
  {word: "done", transcription: "[дан]", translate: "сделано"},
  {word: "door", transcription: "[дор]", translate: "дверь"},
  {word: "doubt", transcription: "[даут]", translate: "сомнение"},
  {word: "down", transcription: "[даун]", translate: "вниз, внизу"},
  {word: "drag", transcription: "[драг]", translate: "тащить"},
  {word: "draw", transcription: "[дро]", translate: "рисовать"},
  {word: "dream", transcription: "[дрим]", translate: "сон, мечта"},
  {word: "dress", transcription: "[дрес]", translate: "платье, одеваться"},
  {word: "drink", transcription: "[дринк]", translate: "пить"},
  {word: "drive", transcription: "[драйв]", translate: "вести машину, водить"},
  {word: "drop", transcription: "[дроп]", translate: "падать, капля"},
  {word: "drove", transcription: "[дроув]", translate: "вел, ехал (о транспортном средстве)"},
  {word: "dry", transcription: "[драй]", translate: "сухой, сушить"},
  {word: "during", transcription: "[дюринг]", translate: "в течение, во время"},
  {word: "each", transcription: "[ич]", translate: "каждый"},
  {word: "ear", transcription: "[иэр]", translate: "ухо"},
  {word: "early", transcription: "[ёрли]", translate: "рано"},
  {word: "easily", transcription: "[изли]", translate: "легко"},
  {word: "easy", transcription: "[изи]", translate: "легкий, простой"},
{word: "eat", transcription: "[ит]", translate: "есть, кушать"},
{word: "edge", transcription: "[эдж]", translate: "край, грань"},
{word: "either", transcription: "[айзэр]", translate: "любой из двух, также, или"},
{word: "else", transcription: "[элс]", translate: "еще, кроме того, иначе"},
{word: "empty", transcription: "[эмпти]", translate: "пустой, опустошать"},
{word: "end", transcription: "[энд]", translate: "конец, заканчивать, оканчивать"},
{word: "enjoy", transcription: "[инджой]", translate: "наслаждаться, получать удовольствие"},
{word: "enough", transcription: "[инаф]", translate: "достаточно, хватит"},
{word: "enter", transcription: "[энтэр]", translate: "войти, входить, вводить"},
{word: "entire", transcription: "[энтайр]", translate: "весь, целый, полный"},
{word: "escape", transcription: "[искэйп]", translate: "избежать, сбежать, убежать"},
{word: "especially", transcription: "[испэшли]", translate: "особенно, в особенности"},
{word: "even", transcription: "[ивн]", translate: "даже, ровный"},
{word: "evening", transcription: "[ивнинг]", translate: "вечер"},
{word: "eventually", transcription: "[ивэнчуэли]", translate: "в конечном итоге, со временем"},
{word: "ever", transcription: "[эвэр]", translate: "когда-либо, вообще"},
{word: "every", transcription: "[эври]", translate: "каждый, всякий"},
{word: "everyone", transcription: "[эвриуан]", translate: "каждый, все"},
{word: "everything", transcription: "[эвризинг]", translate: "все, всё"},
{word: "exactly", transcription: "[игзэктли]", translate: "точно, именно, в точности"},
{word: "except", transcription: "[иксэпт]", translate: "кроме, за исключением"},
{word: "excite", transcription: "[иксайт]", translate: "возбуждать, волновать"},
{word: "exclaim", transcription: "[иксклэйм]", translate: "восклицать, вскрикивать"},
{word: "excuse", transcription: "[иксккьюз]", translate: "извинение, извинить, оправдание"},
{word: "expect", transcription: "[иксптэкт]", translate: "ожидать, рассчитывать"},
{word: "explain", transcription: "[иксплэйн]", translate: "объяснять, разъяснять"},
{word: "expression", transcription: "[иксрэшн]", translate: "выражение, выражение лица"},
{word: "eye", transcription: "[ай]", translate: "глаз"},
{word: "eyebrow", transcription: "[айбрау]", translate: "бровь"},
{word: "face", transcription: "[фэйс]", translate: "лицо, сталкиваться, встречать"},
{word: "fact", transcription: "[фэкт]", translate: "факт, действительность"},
{word: "fall", transcription: "[фол]", translate: "падать, осень, падение"},
{word: "family", transcription: "[фэмли]", translate: "семья, семейство"},
{word: "far", transcription: "[фар]", translate: "далеко, далекий"},
{word: "fast", transcription: "[фаст]", translate: "быстро, поститься, крепкий"},
{word: "father", transcription: "[фазэр]", translate: "отец, родитель"},
{word: "fault", transcription: "[фолт]", translate: "вина, ошибка, недостаток"},
{word: "favorite", transcription: "[фэйврит]", translate: "любимый, предпочитаемый"},
{word: "fear", transcription: "[фир]", translate: "страх, бояться"},
{word: "feel", transcription: "[фил]", translate: "чувствовать, ощущать"},
{word: "feet", transcription: "[фит]", translate: "ноги, ступни"},
{word: "fell", transcription: "[фэлл]", translate: "упал, падал"},
{word: "felt", transcription: "[фэлт]", translate: "чувствовал, ощущал"},
{word: "few", transcription: "[фью]", translate: "несколько, малочисленный"},
{word: "field", transcription: "[филд]", translate: "поле, область"},
{word: "fight", transcription: "[файт]", translate: "драка, борьба, бороться"},
{word: "figure", transcription: "[фигьюр]", translate: "фигура, образ, вычислять"},
{word: "fill", transcription: "[филл]", translate: "заполнять, наполнять"},
{word: "finally", transcription: "[файнэли]", translate: "наконец, в конце концов"},
{word: "find", transcription: "[файнд]", translate: "находить, обнаруживать"},
{word: "fine", transcription: "[файн]", translate: "хорошо, отлично, штраф"},
{word: "finger", transcription: "[финггэр]", translate: "палец"},
{word: "finish", transcription: "[финиш]", translate: "заканчивать, завершать"},
{word: "fire", transcription: "[файр]", translate: "огонь, пожар, стрелять"},
{word: "first", transcription: "[фёрст]", translate: "первый, сначала"},
{word: "fit", transcription: "[фит]", translate: "подходить, соответствовать, годиться"},
{word: "five", transcription: "[файв]", translate: "пять"},
{word: "fix", transcription: "[фикс]", translate: "чинить, фиксировать, ремонтировать"},
{word: "flash", transcription: "[флэш]", translate: "вспышка, сверкать, мелькать"},
{word: "flip", transcription: "[флип]", translate: "переворачивать, перевернуть"},
{word: "floor", transcription: "[флор]", translate: "пол, этаж, напольный"},
{word: "fly", transcription: "[флай]", translate: "летать, лететь, муха"},
{word: "focus", transcription: "[фоукас]", translate: "фокусироваться, сосредотачиваться"},
{word: "follow", transcription: "[фоллоу]", translate: "следовать, следить, идти за"},
{word: "food", transcription: "[фуд]", translate: "еда, пища"},
{word: "foot", transcription: "[фут]", translate: "нога, ступня, фут"},
{word: "for", transcription: "[фор]", translate: "для, за, ради"},
{word: "force", transcription: "[форс]", translate: "сила, заставлять, принуждать"},
{word: "forget", transcription: "[форгэт]", translate: "забывать, позабыть"},
{word: "form", transcription: "[форм]", translate: "форма, создавать, образовывать"},
{word: "forward", transcription: "[форуэрд]", translate: "вперед, передний"},
{word: "found", transcription: "[фаунд]", translate: "находить, основывать, учреждать"},
{word: "four", transcription: "[фор]", translate: "четыре"},
{word: "free", transcription: "[фри]", translate: "свободный, бесплатный, освобождать"},
{word: "friend", transcription: "[френд]", translate: "друг, подруга"},
{word: "from", transcription: "[фром]", translate: "из, от, начиная с"},
{word: "front", transcription: "[франт]", translate: "перед, фронт, передняя часть"},
{word: "frown", transcription: "[фраун]", translate: "нахмуриваться, хмуриться"},
{word: "fuck", transcription: "[фак]", translate: "переспать, трахнуть, ругательство"},
{word: "full", transcription: "[фулл]", translate: "полный, наполненный"},
{word: "fun", transcription: "[фан]", translate: "веселье, забава"},
{word: "funny", transcription: "[фанни]", translate: "смешной, комичный"},
{word: "further", transcription: "[фёрзэр]", translate: "дальше, далее"},
{word: "game", transcription: "[гэйм]", translate: "игра, охота"},
{word: "gasp", transcription: "[гасп]", translate: "вздохнуть, ахнуть"},
{word: "gave", transcription: "[гэйв]", translate: "дал, отдавал, давал"},
{word: "gaze", transcription: "[гэйз]", translate: "взгляд, смотреть"},
{word: "gently", transcription: "[джэнтли]", translate: "мягко, нежно"},
{word: "get", transcription: "[гэт]", translate: "получать, доставать, становиться"},
{word: "giggle", transcription: "[гигл]", translate: "хихикать, хихикание"},
{word: "girl", transcription: "[гёрл]", translate: "девушка, девочка"},
{word: "girlfriend", transcription: "[гёрлфрэнд]", translate: "подруга, девушка"},
{word: "give", transcription: "[гив]", translate: "давать, отдавать"},
{word: "given", transcription: "[гивн]", translate: "данный, предоставленный"},
{word: "glad", transcription: "[глэд]", translate: "рад, радостный"},
{word: "glance", transcription: "[гланс]", translate: "взгляд, бросить взгляд"},
{word: "glare", transcription: "[глэр]", translate: "ярко светить, сердитый взгляд"},
{word: "glass", transcription: "[глас]", translate: "стекло, бокал, стакан"},
{word: "go", transcription: "[гоу]", translate: "идти, ехать, двигаться"},
{word: "God", transcription: "[год]", translate: "Бог, божество"},
{word: "gone", transcription: "[гон]", translate: "ушел, ушедший, исчезнувший"},
{word: "gonna", transcription: "[гана]", translate: "собирается, намеревается, буду"},
{word: "good", transcription: "[гуд]", translate: "хороший, добрый, благой"},
{word: "got", transcription: "[гот]", translate: "получил, имел, добывать"},
{word: "gotten", transcription: "[готн]", translate: "полученный, приобретенный"},
{word: "grab", transcription: "[грэб]", translate: "хватать, схватить, ловить"},
{word: "great", transcription: "[грэйт]", translate: "великолепный, отличный, большой"},
{word: "green", transcription: "[грин]", translate: "зеленый, зелень"},
{word: "greet", transcription: "[грит]", translate: "приветствовать, встречать"},
{word: "grey", transcription: "[грэй]", translate: "серый, седой"},
{word: "grin", transcription: "[грин]", translate: "ухмыляться, усмешка"},
{word: "grip", transcription: "[грип]", translate: "захват, сцепление, хватка"},
{word: "groan", transcription: "[гроун]", translate: "стон, стонать, охать"},
{word: "ground", transcription: "[граунд]", translate: "земля, основание, почва"},
{word: "group", transcription: "[групп]", translate: "группа, группировать"},
{word: "grow", transcription: "[гроу]", translate: "расти, вырастать, выращивать"},
{word: "guard", transcription: "[гард]", translate: "сторожить, охранять, стража"},
{word: "guess", transcription: "[гэс]", translate: "угадывать, догадываться, предполагать"},
{word: "gun", transcription: "[ган]", translate: "пистолет, оружие, ружье"},
{word: "guy", transcription: "[гай]", translate: "парень, человек, тип"},
{word: "had", transcription: "[хэд]", translate: "имел, владел"},
{word: "hadn't", transcription: "[хэдэнт]", translate: "не имел"},
{word: "hair", transcription: "[хэр]", translate: "волосы, волосяной покров"},
{word: "half", transcription: "[хаф]", translate: "половина, наполовину"},
{word: "hall", transcription: "[хол]", translate: "зал, коридор, вестибюль"},
{word: "hallway", transcription: "[холлуэй]", translate: "коридор, холл"},
{word: "hand", transcription: "[хэнд]", translate: "рука, кисть руки"},
{word: "handle", transcription: "[хэндл]", translate: "ручка, управлять, обращаться"},
{word: "hang", transcription: "[хэнг]", translate: "висеть, вешать, повесить"},
{word: "happen", transcription: "[хэпн]", translate: "случаться, происходить"},
{word: "happy", transcription: "[хэппи]", translate: "счастливый, радостный"},
{word: "hard", transcription: "[хард]", translate: "трудный, жесткий, твердый"},
{word: "has", transcription: "[хэз]", translate: "имеет, обладает"},
{word: "hate", transcription: "[хэйт]", translate: "ненавидеть, ненависть"},
{word: "have", transcription: "[хэв]", translate: "иметь, обладать"},
{word: "haven't", transcription: "[хэвнт]", translate: "не имеет, не имею"},
{word: "he", transcription: "[хи]", translate: "он, это"},
{word: "he'd", transcription: "[хид]", translate: "он бы, он имел бы"},
{word: "he's", transcription: "[хиз]", translate: "он есть, он имеет"},
{word: "head", transcription: "[хэд]", translate: "голова, глава"},
{word: "hear", transcription: "[хир]", translate: "слышать, услышать"},
{word: "heard", transcription: "[хёрд]", translate: "слышал, слышалось"},
{word: "heart", transcription: "[харт]", translate: "сердце, душа"},
{word: "heavy", transcription: "[хэви]", translate: "тяжелый, тяжесть"},
{word: "held", transcription: "[хэлд]", translate: "держал, удерживал"},
{word: "hell", transcription: "[хэлл]", translate: "ад, преисподняя"},
{word: "hello", transcription: "[хэллоу]", translate: "привет, здравствуйте"},
{word: "help", transcription: "[хэлп]", translate: "помощь, помогать, помочь"},
{word: "her", transcription: "[хёр]", translate: "ее, ей, ее"},
{word: "here", transcription: "[хир]", translate: "здесь, сюда, тут"},
{word: "herself", transcription: "[хёрсэлф]", translate: "себя, сама, саму"},
{word: "hey", transcription: "[хэй]", translate: "привет, эй"},
{word: "hi", transcription: "[хай]", translate: "привет, здравствуйте"},
{word: "hide", transcription: "[хайд]", translate: "прятаться, скрывать, утаить"},
{word: "high", transcription: "[хай]", translate: "высокий, высоко"},
{word: "him", transcription: "[хим]", translate: "его, ему, ему"},
{word: "himself", transcription: "[химсэлф]", translate: "себя, сам, самого себя"},
{word: "his", transcription: "[хиз]", translate: "его, принадлежащий ему"},
{word: "hit", transcription: "[хит]", translate: "удар, ударять, бить"},
{word: "hold", transcription: "[холд]", translate: "держать, хватка"},
{word: "home", transcription: "[хоум]", translate: "дом, жилище"},
{word: "hope", transcription: "[хоуп]", translate: "надежда, надеяться, надежда"},
{word: "horse", transcription: "[хорс]", translate: "лошадь, конь"},
{word: "hospital", transcription: "[хоспитл]", translate: "больница, госпиталь"},
{word: "hot", transcription: "[хот]", translate: "горячий, жарко, знойный"},
{word: "hour", transcription: "[ауэр]", translate: "час, один час"},
{word: "house", transcription: "[хаус]", translate: "дом, здание"},
{word: "how", transcription: "[хау]", translate: "как, каким образом, насколько"},
{word: "however", transcription: "[хауэвэр]", translate: "однако, тем не менее, все же"},
{word: "hug", transcription: "[хаг]", translate: "обнимать, объятие"},
{word: "huge", transcription: "[хьюдж]", translate: "огромный, громадный"},
{word: "huh", transcription: "[ха]", translate: "эй, что, а"},
{word: "human", transcription: "[хьюмэн]", translate: "человек, человеческий"},
{word: "hundred", transcription: "[хандрид]", translate: "сто, сотня"},
{word: "hung", transcription: "[ханг]", translate: "висел, повешенный"},
{word: "hurry", transcription: "[хари]", translate: "торопиться, спешить, спешка"},
{word: "hurt", transcription: "[хёрт]", translate: "причинять боль, больно, ранить"},
{word: "I", transcription: "[ай]", translate: "я, мне"},
{word: "I'd", transcription: "[айд]", translate: "я бы, я имел бы"},
{word: "I'll", transcription: "[айлл]", translate: "я буду, я сделаю"},
{word: "I'm", transcription: "[айм]", translate: "я есть, я нахожусь"},
{word: "I've", transcription: "[айв]", translate: "у меня есть, я имею"},
{word: "ice", transcription: "[айс]", translate: "лед, ледяной"},
{word: "idea", transcription: "[айдиа]", translate: "идея, понятие, мысль"},
{word: "if", transcription: "[иф]", translate: "если, в случае"},
{word: "ignore", transcription: "[игнор]", translate: "игнорировать, пренебрегать"},
{word: "imagine", transcription: "[имэджин]", translate: "воображать, представлять"},
{word: "immediately", transcription: "[имидиэтли]", translate: "немедленно, сразу же"},
{word: "important", transcription: "[импортнт]", translate: "важный, значительный"},
{word: "in", transcription: "[ин]", translate: "в, внутри"},
{word: "inside", transcription: "[инсайд]", translate: "внутри, внутрь"},
{word: "instead", transcription: "[инстэд]", translate: "вместо, вместо этого"},
{word: "interest", transcription: "[интрэст]", translate: "интерес, интересовать, заинтересованность"},
{word: "interrupt", transcription: "[интэрапт]", translate: "перебивать, прерывать, нарушать"},
{word: "into", transcription: "[инту]", translate: "в, внутрь, до"},
{word: "is", transcription: "[из]", translate: "есть, является, это"},
{word: "isn't", transcription: "[изнт]", translate: "не является, не есть"},
{word: "it", transcription: "[ит]", translate: "это, он, она, оно"},
{word: "it's", transcription: "[итс]", translate: "это, это есть, это есть"},
{word: "its", transcription: "[итс]", translate: "его, ее, свой, своя"},
 {word: "jacket", transcription: "[джэкит]", translation: "куртка"},
 {word: "jeans", transcription: "[джинз]", translation: "джинсы"},
 {word: "jerk", transcription: "[джёрк]", translation: "придурок, толчок"},
 {word: "job", transcription: "[джоб]", translation: "работа"},
 {word: "join", transcription: "[джойн]", translation: "присоединяться"},
 {word: "joke", transcription: "[джоук]", translation: "шутка"},
 {word: "jump", transcription: "[джамп]", translation: "прыгать"},
 {word: "just", transcription: "[джаст]", translation: "просто, только что"},
 {word: "keep", transcription: "[кип]", translation: "держать, сохранять"},
 {word: "kept", transcription: "[кепт]", translation: "держал, сохранял"},
 {word: "key", transcription: "[ки]", translation: "ключ"},
 {word: "kick", transcription: "[кик]", translation: "ударять ногой"},
 {word: "kid", transcription: "[кид]", translation: "ребенок"},
 {word: "kill", transcription: "[кил]", translation: "убивать"},
 {word: "kind", transcription: "[кайнд]", translation: "добрый, вид"},
 {word: "kiss", transcription: "[кис]", translation: "целовать"},
 {word: "kitchen", transcription: "[кичин]", translation: "кухня"},
 {word: "knee", transcription: "[ни]", translation: "колено"},
 {word: "knew", transcription: "[ню]", translation: "знал"},
 {word: "knock", transcription: "[нок]", translation: "стучать"},
 {word: "know", transcription: "[ноу]", translation: "знать"},
 {word: "known", transcription: "[ноун]", translation: "известный"},
 {word: "lady", transcription: "[лэди]", translation: "леди, дама"},
 {word: "land", transcription: "[лэнд]", translation: "земля"},
 {word: "large", transcription: "[лардж]", translation: "большой"},
 {word: "last", transcription: "[ласт]", translation: "последний"},
 {word: "late", transcription: "[лэйт]", translation: "поздний"},
 {word: "laugh", transcription: "[лаф]", translation: "смех, смеяться"},
 {word: "lay", transcription: "[лэй]", translation: "лежать"},
 {word: "lead", transcription: "[лид]", translation: "вести"},
 {word: "lean", transcription: "[лин]", translation: "наклоняться"},
 {word: "learn", transcription: "[лёрн]", translation: "учиться, узнавать"},
 {word: "least", transcription: "[лист]", translation: "наименьший, по крайней мере"},
 {word: "leave", transcription: "[лив]", translation: "оставлять, уходить"},
 {word: "led", transcription: "[лед]", translation: "вел, руководил"},
 {word: "left", transcription: "[лефт]", translation: "оставил, ушел"},
 {word: "leg", transcription: "[лег]", translation: "нога"},
 {word: "less", transcription: "[лес]", translation: "менее"},
 {word: "let", transcription: "[лет]", translation: "позволять"},
 {word: "letter", transcription: "[летэр]", translation: "письмо"},
 {word: "lie", transcription: "[лай]", translation: "лгать, ложь"},
 {word: "life", transcription: "[лайф]", translation: "жизнь"},
 {word: "lift", transcription: "[лифт]", translation: "поднимать"},
 {word: "light", transcription: "[лайт]", translation: "свет, светлый"},
 {word: "like", transcription: "[лайк]", translation: "как, как будто"},
 {word: "line", transcription: "[лайн]", translation: "линия, строка"},
 {word: "lip", transcription: "[лип]", translation: "губа"},
 {word: "listen", transcription: "[лисн]", translation: "слушать"},
 {word: "little", transcription: "[литл]", translation: "маленький, немного"},
 {word: "live", transcription: "[лив]", translation: "жить"},
 {word: "lock", transcription: "[лок]", translation: "замок, запирать"},
 {word: "locker", transcription: "[локэр]", translation: "ящик, шкафчик"},
 {word: "long", transcription: "[лонг]", translation: "длинный, долгий"},
 {word: "look", transcription: "[лук]", translation: "смотреть, взгляд"},
 {word: "lose", transcription: "[луз]", translation: "терять"},
 {word: "lost", transcription: "[лост]", translation: "потерянный"},
 {word: "lot", transcription: "[лот]", translation: "много"},
 {word: "loud", transcription: "[лауд]", translation: "громкий"},
 {word: "love", transcription: "[лав]", translation: "любовь, любить"},
 {word: "low", transcription: "[лоу]", translation: "низкий"},
 {word: "lunch", transcription: "[ланч]", translation: "ланч, обед"},
 {word: "mad", transcription: "[мэд]", translation: "безумный, злой"},
 {word: "made", transcription: "[мэйд]", translation: "сделанный, сделал"},
 {word: "make", transcription: "[мэйк]", translation: "делать"},
 {word: "man", transcription: "[мэн]", translation: "человек, мужчина"},
 {word: "manage", transcription: "[мэнидж]", translation: "управлять, справляться"},
 {word: "many", transcription: "[мэни]", translation: "много"},
 {word: "mark", transcription: "[марк]", translation: "метка, отметка"},
 {word: "marry", transcription: "[мэри]", translation: "жениться, выходить замуж"},
 {word: "match", transcription: "[мэч]", translation: "матч, соответствовать"},
 {word: "matter", transcription: "[мэтэр]", translation: "дело, вопрос, иметь значение"},
 {word: "may", transcription: "[мэй]", translation: "мочь, возможно"},
 {word: "maybe", transcription: "[мэйби]", translation: "возможно, может быть"},
 {word: "me", transcription: "[ми]", translation: "меня, мне"},
 {word: "mean", transcription: "[мин]", translation: "означать, иметь в виду"},
 {word: "meant", transcription: "[мент]", translation: "подразумевал, имел в виду"},
 {word: "meet", transcription: "[мит]", translation: "встречать"},
 {word: "memory", transcription: "[мемори]", translation: "память"},
 {word: "men", transcription: "[мен]", translation: "мужчины"},
 {word: "mention", transcription: "[меншн]", translation: "упоминать"},
 {word: "met", transcription: "[мет]", translation: "встречал"},
 {word: "middle", transcription: "[мидл]", translation: "середина"},
 {word: "might", transcription: "[майт]", translation: "мог бы, возможно"},
 {word: "mind", transcription: "[майнд]", translation: "разум, ум"},
 {word: "mine", transcription: "[майн]", translation: "мой, шахта"},
 {word: "minute", transcription: "[минит]", translation: "минута"},
 {word: "mirror", transcription: "[мирэр]", translation: "зеркало"},
 {word: "miss", transcription: "[мис]", translation: "скучать, пропустить"},
 {word: "mom", transcription: "[мам]", translation: "мама"},
 {word: "moment", transcription: "[моумэнт]", translation: "момент"},
 {word: "money", transcription: "[мани]", translation: "деньги"},
 {word: "month", transcription: "[манс]", translation: "месяц"},
 {word: "mood", transcription: "[муд]", translation: "настроение"},
 {word: "more", transcription: "[мор]", translation: "больше"},
 {word: "morning", transcription: "[морнинг]", translation: "утро"},
 {word: "most", transcription: "[моуст]", translation: "большинство, самый"},
 {word: "mother", transcription: "[мазэр]", translation: "мать"},
 {word: "mouth", transcription: "[мауз]", translation: "рот"},
 {word: "move", transcription: "[мув]", translation: "двигаться"},
 {word: "movie", transcription: "[муви]", translation: "фильм"},
 {word: "Mr.", transcription: "[мистэр]", translation: "господин"},
 {word: "Mrs.", transcription: "[мисиз]", translation: "госпожа"},
 {word: "much", transcription: "[мач]", translation: "много"},
 {word: "mum", transcription: "[мам]", translation: "мама"},
 {word: "mumble", transcription: "[мамбл]", translation: "бормотать"},
 {word: "music", transcription: "[мьюзик]", translation: "музыка"},
 {word: "must", transcription: "[маст]", translation: "должен, обязан"},
 {word: "mutter", transcription: "[матэр]", translation: "бормотать, бурчать"},
 {word: "my", transcription: "[май]", translation: "мой"},
 {word: "myself", transcription: "[майсэлф]", translation: "себя, сам"},
 {word: "name", transcription: "[нэйм]", translation: "имя"},
 {word: "near", transcription: "[ниэр]", translation: "близко"},
 {word: "nearly", transcription: "[нирли]", translation: "почти"},
 {word: "neck", transcription: "[нек]", translation: "шея, шею"},
 {word: "need", transcription: "[нид]", translation: "нуждаться, нужно"},
 {word: "nervous", transcription: "[нёрвэс]", translation: "нервный"},
 {word: "never", transcription: "[невэр]", translation: "никогда"},
 {word: "new", transcription: "[ню]", translation: "новый"},
 {word: "next", transcription: "[некст]", translation: "следующий"},
 {word: "nice", transcription: "[найс]", translation: "хороший, приятный"},
 {word: "night", transcription: "[найт]", translation: "ночь"},
 {word: "no", transcription: "[ноу]", translation: "нет"},
 {word: "nod", transcription: "[нод]", translation: "кивок"},
 {word: "noise", transcription: "[нойз]", translation: "шум"},
 {word: "none", transcription: "[нан]", translation: "нет никакого"},
 {word: "normal", transcription: "[нормэл]", translation: "нормальный"},
 {word: "nose", transcription: "[ноуз]", translation: "нос"},
 {word: "not", transcription: "[нот]", translation: "не"},
 {word: "note", transcription: "[ноут]", translation: "заметка, нота"},
 {word: "nothing", transcription: "[назинг]", translation: "ничего"},
 {word: "notice", transcription: "[ноутис]", translation: "замечать"},
 {word: "now", transcription: "[нау]", translation: "сейчас"},
 {word: "number", transcription: "[намбэр]", translation: "номер"},
 {word: "obviously", transcription: "[обвиэсли]", translation: "очевидно"},
 {word: "of", transcription: "[ов]", translation: "из, от, о"},
 {word: "off", transcription: "[оф]", translation: "выключено"},
 {word: "offer", transcription: "[офэр]", translation: "предложение, предлагать"},
 {word: "office", transcription: "[офис]", translation: "офис"},
 {word: "often", transcription: "[офн]", translation: "часто"},
 {word: "oh", transcription: "[оу]", translation: "о, ах"},
 {word: "okay", transcription: "[оукэй]", translation: "хорошо, ладно"},
 {word: "old", transcription: "[оулд]", translation: "старый"},
 {word: "on", transcription: "[он]", translation: "на, в"},
 {word: "once", transcription: "[ванс]", translation: "однажды"},
 {word: "one", transcription: "[ван]", translation: "один"},
 {word: "only", transcription: "[оунли]", translation: "только"},
 {word: "onto", transcription: "[онтэ]", translation: "на, к"},
 {word: "open", transcription: "[оупн]", translation: "открыть, открыто"},
 {word: "or", transcription: "[ор]", translation: "или"},
 {word: "order", transcription: "[ордэр]", translation: "порядок, заказ"},
 {word: "other", transcription: "[азэр]", translation: "другой"},
 {word: "our", transcription: "[ауэр]", translation: "наш"},
 {word: "out", transcription: "[аут]", translation: "вне, из"},
 {word: "outside", transcription: "[аутсайд]", translation: "снаружи"},
 {word: "over", transcription: "[оувэр]", translation: "над, сверх"},
 {word: "own", transcription: "[оун]", translation: "свой"},
 {word: "pack", transcription: "[пэк]", translation: "пачка, упаковывать"},
 {word: "pain", transcription: "[пэйн]", translation: "боль"},
 {word: "paint", transcription: "[пэйнт]", translation: "красить, краска"},
 {word: "pair", transcription: "[пэр]", translation: "пара"},
 {word: "pants", transcription: "[пэнтс]", translation: "брюки"},
 {word: "paper", transcription: "[пэйпэр]", translation: "бумага"},
 {word: "parents", transcription: "[пэрэнтс]", translation: "родители"},
 {word: "park", transcription: "[парк]", translation: "парк, парковать"},
 {word: "part", transcription: "[парт]", translation: "часть"},
 {word: "party", transcription: "[парти]", translation: "вечеринка"},
 {word: "pass", transcription: "[пас]", translation: "проходить, пройти"},
 {word: "past", transcription: "[паст]", translation: "прошлое"},
 {word: "pause", transcription: "[поз]", translation: "пауза"},
 {word: "pay", transcription: "[пэй]", translation: "платить"},
 {word: "people", transcription: "[пипл]", translation: "люди"},
 {word: "perfect", transcription: "[пёрфикт]", translation: "идеальный"},
 {word: "perhaps", transcription: "[пэрхэпс]", translation: "возможно"},
 {word: "person", transcription: "[пёрсн]", translation: "человек"},
 {word: "phone", transcription: "[фоун]", translation: "телефон"},
 {word: "pick", transcription: "[пик]", translation: "выбирать, поднимать"},
 {word: "picture", transcription: "[пикчэр]", translation: "картина, фото"},
 {word: "piece", transcription: "[пис]", translation: "кусок"},
 {word: "pink", transcription: "[пинк]", translation: "розовый"},
 {word: "piss", transcription: "[пис]", translation: "писать"},
 {word: "place", transcription: "[плэйс]", translation: "место"},
 {word: "plan", transcription: "[плэн]", translation: "план"},
 {word: "play", transcription: "[плэй]", translation: "играть, игра"},
 {word: "please", transcription: "[плиз]", translation: "пожалуйста"},
 {word: "pocket", transcription: "[покит]", translation: "карман"},
 {word: "point", transcription: "[пойнт]", translation: "точка, указывать"},
 {word: "police", transcription: "[полис]", translation: "полиция"},
 {word: "pop", transcription: "[поп]", translation: "поп, взрыв"},
 {word: "position", transcription: "[пэзишн]", translation: "позиция"},
 {word: "possible", transcription: "[посибл]", translation: "возможный"},
 {word: "power", transcription: "[пауэр]", translation: "сила, мощь"},
 {word: "practically", transcription: "[прэктикли]", translation: "практически"},
 {word: "present", transcription: "[презнт]", translation: "присутствующий, подарок"},
 {word: "press", transcription: "[пресс]", translation: "нажимать, пресса"},
 {word: "pretend", transcription: "[притэнд]", translation: "притворяться"},
 {word: "pretty", transcription: "[прити]", translation: "красивый"},
 {word: "probably", transcription: "[пробэбли]", translation: "возможно"},
 {word: "problem", transcription: "[проблэм]", translation: "проблема"},
 {word: "promise", transcription: "[промис]", translation: "обещание, обещать"},
 {word: "pull", transcription: "[пул]", translation: "тянуть, тащить"},
 {word: "punch", transcription: "[панч]", translation: "удар"},
 {word: "push", transcription: "[пуш]", translation: "толкать"},
 {word: "put", transcription: "[пут]", translation: "класть, ставить"},
 {word: "question", transcription: "[куэсчн]", translation: "вопрос"},
 {word: "quick", transcription: "[куик]", translation: "быстрый"},
 {word: "quickly", transcription: "[куикли]", translation: "быстро"},
 {word: "quiet", transcription: "[куайэт]", translation: "тихий"},
 {word: "quietly", transcription: "[куайэтли]", translation: "тихо"},
 {word: "quite", transcription: "[куайт]", translation: "вполне"},
 {word: "race", transcription: "[рэйс]", translation: "гонка, раса"},
 {word: "rain", transcription: "[рэйн]", translation: "дождь"},
 {word: "raise", transcription: "[рэйз]", translation: "поднимать"},
 {word: "ran", transcription: "[рэн]", translation: "бежал"},
 {word: "rang", transcription: "[рэнг]", translation: "звонил"},
 {word: "rather", transcription: "[разэр]", translation: "лучше, скорее"},
 {word: "reach", transcription: "[рич]", translation: "достигать"},
 {word: "read", transcription: "[рид]", translation: "читать"},
 {word: "ready", transcription: "[реди]", translation: "готовый"},
 {word: "real", transcription: "[риэл]", translation: "настоящий"},
 {word: "realize", transcription: "[риэлайз]", translation: "понимать"},
 {word: "really", transcription: "[риэли]", translation: "действительно"},
 {word: "reason", transcription: "[ризн]", translation: "причина, разум"},
 {word: "recognize", transcription: "[рекэгнайз]", translation: "узнавать"},
 {word: "red", transcription: "[ред]", translation: "красный"},
 {word: "relationship", transcription: "[рилэйшншип]", translation: "отношение"},
 {word: "relax", transcription: "[рилэкс]", translation: "расслабиться"},
 {word: "remain", transcription: "[римэйн]", translation: "оставаться"},
 {word: "remember", transcription: "[римембэр]", translation: "помнить"},
 {word: "remind", transcription: "[римайнд]", translation: "напоминать"},
 {word: "repeat", transcription: "[рипит]", translation: "повторять"},
 {word: "reply", transcription: "[риплай]", translation: "ответ"},
 {word: "respond", transcription: "[риспонд]", translation: "отвечать"},
 {word: "rest", transcription: "[рест]", translation: "отдых"},
 {word: "return", transcription: "[ритёрн]", translation: "возвращение"},
 {word: "ride", transcription: "[райд]", translation: "езда, катание"},
 {word: "right", transcription: "[райт]", translation: "правильный, право"},
 {word: "ring", transcription: "[ринг]", translation: "кольцо, звонить"},
 {word: "road", transcription: "[роуд]", translation: "дорога"},
 {word: "rock", transcription: "[рок]", translation: "камень, качать"},
 {word: "roll", transcription: "[роул]", translation: "катиться, рулон"},
 {word: "room", transcription: "[рум]", translation: "комната"},
 {word: "rose", transcription: "[роуз]", translation: "роза"},
 {word: "round", transcription: "[раунд]", translation: "круглый, раунд"},
 {word: "rub", transcription: "[раб]", translation: "тереть"},
 {word: "run", transcription: "[ран]", translation: "бежать"},
 {word: "rush", transcription: "[раш]", translation: "спешить"},
 {word: "sad", transcription: "[сэд]", translation: "грустный"},
 {word: "safe", transcription: "[сэйф]", translation: "безопасный"},
 {word: "said", transcription: "[сэд]", translation: "сказал"},
 {word: "same", transcription: "[сэйм]", translation: "тот же, такой же"},
 {word: "sat", transcription: "[сэт]", translation: "сидел"},
 {word: "save", transcription: "[сэйв]", translation: "спасать, сохранять"},
 {word: "saw", transcription: "[со]", translation: "пила, видел"},
 {word: "say", transcription: "[сэй]", translation: "говорить"},
 {word: "scare", transcription: "[скэр]", translation: "пугать"},
 {word: "school", transcription: "[скул]", translation: "школа"},
 {word: "scream", transcription: "[скрим]", translation: "кричать"},
 {word: "search", transcription: "[сёрч]", translation: "искать"},
 {word: "seat", transcription: "[сит]", translation: "место, сиденье"},
 {word: "second", transcription: "[секэнд]", translation: "второй, секунда"},
 {word: "see", transcription: "[си]", translation: "видеть"},
 {word: "seem", transcription: "[сим]", translation: "казаться"},
 {word: "seen", transcription: "[син]", translation: "виденный"},
 {word: "self", transcription: "[сэлф]", translation: "сам"},
 {word: "send", transcription: "[сенд]", translation: "отправлять"},
 {word: "sense", transcription: "[сенс]", translation: "чувство, смысл"},
 {word: "sent", transcription: "[сент]", translation: "отправил"},
 {word: "serious", transcription: "[сириэс]", translation: "серьезный"},
 {word: "seriously", transcription: "[сириэсли]", translation: "серьезно"},
 {word: "set", transcription: "[сет]", translation: "устанавливать, набор"},
 {word: "settle", transcription: "[сетл]", translation: "улаживать"},
 {word: "seven", transcription: "[севн]", translation: "семь"},
 {word: "several", transcription: "[севрэл]", translation: "несколько"},
 {word: "shadow", transcription: "[шэдоу]", translation: "тень"},
 {word: "shake", transcription: "[шэйк]", translation: "трясти"},
 {word: "share", transcription: "[шэр]", translation: "делиться"},
 {word: "she", transcription: "[ши]", translation: "она"},
 {word: "she'd", transcription: "[шид]", translation: "она бы"},
 {word: "she's", transcription: "[шиз]", translation: "она есть"},
 {word: "shift", transcription: "[шифт]", translation: "смена"},
 {word: "shirt", transcription: "[шёрт]", translation: "рубашка"},
 {word: "shit", transcription: "[шит]", translation: "дерьмо, фекалии"},
 {word: "shock", transcription: "[шок]", translation: "шок"},
 {word: "shoe", transcription: "[шу]", translation: "туфля"},
 {word: "shook", transcription: "[шук]", translation: "тряс, трясся"},
 {word: "shop", transcription: "[шоп]", translation: "магазин"},
 {word: "short", transcription: "[шорт]", translation: "короткий"},
 {word: "shot", transcription: "[шот]", translation: "выстрел"},
 {word: "should", transcription: "[шуд]", translation: "должен"},
 {word: "shoulder", transcription: "[шоулдэр]", translation: "плечо"},
 {word: "shouldn't", transcription: "[шудント]", translation: "не следует"},
 {word: "shout", transcription: "[шаут]", translation: "кричать"},
 {word: "shove", transcription: "[шав]", translation: "толкать"},
 {word: "show", transcription: "[шоу]", translation: "показывать, шоу"},
 {word: "shower", transcription: "[шауэр]", translation: "душ"},
 {word: "shrug", transcription: "[шраг]", translation: "пожимать плечами"},
 {word: "shut", transcription: "[шат]", translation: "закрыть"},
 {word: "sick", transcription: "[сик]", translation: "больной, тошнота"},
 {word: "side", transcription: "[сайд]", translation: "сторона"},
 {word: "sigh", transcription: "[сай]", translation: "вздох"},
 {word: "sight", transcription: "[сайт]", translation: "вид, зрение"},
 {word: "sign", transcription: "[сайн]", translation: "знак"},
 {word: "silence", transcription: "[сайлэнс]", translation: "молчание"},
 {word: "silent", transcription: "[сайлэнт]", translation: "тихий, молчаливый"},
 {word: "simply", transcription: "[симпли]", translation: "просто"},
 {word: "since", transcription: "[синс]", translation: "с тех пор, так как"},
 {word: "single", transcription: "[сингл]", translation: "один, холостой"},
 {word: "sir", transcription: "[сёр]", translation: "сэр"},
 {word: "sister", transcription: "[систэр]", translation: "сестра"},
 {word: "sit", transcription: "[сит]", translation: "сидеть"},
 {word: "situation", transcription: "[ситчуэйшн]", translation: "ситуация"},
 {word: "six", transcription: "[сикс]", translation: "шесть"},
 {word: "skin", transcription: "[скин]", translation: "кожа"},
 {word: "sky", transcription: "[скай]", translation: "небо"},
 {word: "slam", transcription: "[слэм]", translation: "хлопнуть"},
 {word: "sleep", transcription: "[слип]", translation: "спать"},
 {word: "slightly", transcription: "[слайтли]", translation: "немного"},
 {word: "slip", transcription: "[слип]", translation: "скользить"},
 {word: "slow", transcription: "[слоу]", translation: "медленный"},
 {word: "slowly", transcription: "[слоули]", translation: "медленно"},
 {word: "small", transcription: "[смол]", translation: "маленький"},
 {word: "smell", transcription: "[смэл]", translation: "запах"},
 {word: "smile", transcription: "[смайл]", translation: "улыбка"},
 {word: "smirk", transcription: "[смёрк]", translation: "ухмылка"},
 {word: "smoke", transcription: "[смоук]", translation: "курить, дым"},
 {word: "snap", transcription: "[снэп]", translation: "щелчок"},
 {word: "so", transcription: "[соу]", translation: "так, таким образом"},
 {word: "soft", transcription: "[софт]", translation: "мягкий"},
 {word: "softly", transcription: "[софтли]", translation: "мягко"},
 {word: "some", transcription: "[сам]", translation: "несколько"},
 {word: "somehow", transcription: "[самхау]", translation: "каким-то образом"},
 {word: "someone", transcription: "[самван]", translation: "кто-то"},
 {word: "something", transcription: "[самсинг]", translation: "что-то"},
 {word: "sometimes", transcription: "[самтаймз]", translation: "иногда"},
 {word: "somewhere", transcription: "[самуэр]", translation: "где-то"},
 {word: "son", transcription: "[сан]", translation: "сын"},
 {word: "song", transcription: "[сонг]", translation: "песня"},
 {word: "soon", transcription: "[сун]", translation: "скоро"},
 {word: "sorry", transcription: "[сори]", translation: "извини, сожалею"},
 {word: "sort", transcription: "[сорт]", translation: "сорт, вид"},
 {word: "sound", transcription: "[саунд]", translation: "звук"},
 {word: "space", transcription: "[спэйс]", translation: "пространство"},
 {word: "speak", transcription: "[спик]", translation: "говорить"},
 {word: "spend", transcription: "[спенд]", translation: "проводить (время)"},
 {word: "spent", transcription: "[спент]", translation: "провёл"},
 {word: "spoke", transcription: "[споук]", translation: "говорил"},
 {word: "spot", transcription: "[спот]", translation: "место"},
 {word: "stair", transcription: "[стэр]", translation: "лестница"},
 {word: "stand", transcription: "[стэнд]", translation: "стоять"},
 {word: "star", transcription: "[стар]", translation: "звезда"},
 {word: "stare", transcription: "[стэр]", translation: "пялиться, смотреть пристально"},
 {word: "start", transcription: "[старт]", translation: "начинать"},
 {word: "state", transcription: "[стэйт]", translation: "состояние, государство"},
 {word: "stay", transcription: "[стэй]", translation: "оставаться"},
 {word: "step", transcription: "[степ]", translation: "шаг"},
 {word: "stick", transcription: "[стик]", translation: "палка, приклеивать"},
 {word: "still", transcription: "[стил]", translation: "все еще"},
 {word: "stomach", transcription: "[стамэк]", translation: "живот, желудок"},
 {word: "stood", transcription: "[студ]", translation: "стоял"},
 {word: "stop", transcription: "[стоп]", translation: "останавливаться"},
 {word: "store", transcription: "[стор]", translation: "магазин"},
 {word: "story", transcription: "[стори]", translation: "рассказ, история"},
 {word: "straight", transcription: "[стрэйт]", translation: "прямо, прямой"},
 {word: "strange", transcription: "[стрэйндж]", translation: "странный"},
 {word: "street", transcription: "[стрит]", translation: "улица"},
 {word: "strong", transcription: "[стронг]", translation: "сильный"},
 {word: "struggle", transcription: "[страгл]", translation: "бороться, борьба"},
 {word: "stuck", transcription: "[стак]", translation: "застрял"},
 {word: "student", transcription: "[стьюдент]", translation: "студент"},
 {word: "study", transcription: "[стади]", translation: "учиться, исследование"},
 {word: "stuff", transcription: "[стаф]", translation: "вещи, всякая фигня"},
 {word: "stupid", transcription: "[стьюпид]", translation: "глупый"},
 {word: "such", transcription: "[сач]", translation: "такой, подобный"},
 {word: "suck", transcription: "[сак]", translation: "сосать, отстой"},
 {word: "sudden", transcription: "[садн]", translation: "внезапный"},
 {word: "suddenly", transcription: "[садли]", translation: "внезапно"},
 {word: "suggest", transcription: "[сэджест]", translation: "предлагать"},
 {word: "summer", transcription: "[самэр]", translation: "лето"},
 {word: "sun", transcription: "[сан]", translation: "солнце"},
 {word: "suppose", transcription: "[сэпоуз]", translation: "полагать"},
 {word: "sure", transcription: "[шуэр]", translation: "уверенный"},
 {word: "surprise", transcription: "[сэрпрайз]", translation: "сюрприз"},
 {word: "surround", transcription: "[сэраунд]", translation: "окружать"},
 {word: "sweet", transcription: "[свит]", translation: "сладкий"},
 {word: "table", transcription: "[тэйбл]", translation: "стол"},
 {word: "take", transcription: "[тэйк]", translation: "брать"},
 {word: "taken", transcription: "[тэйкн]", translation: "взятый"},
 {word: "talk", transcription: "[ток]", translation: "разговаривать"},
 {word: "tall", transcription: "[тол]", translation: "высокий"},
 {word: "teacher", transcription: "[тичэр]", translation: "учитель"},
 {word: "team", transcription: "[тим]", translation: "команда"},
 {word: "tear", transcription: "[тиэр]", translation: "слеза"},
 {word: "teeth", transcription: "[тис]", translation: "зубы"},
 {word: "tell", transcription: "[тэл]", translation: "говорить, рассказывать"},
 {word: "ten", transcription: "[тэн]", translation: "десять"},
 {word: "than", transcription: "[зэн]", translation: "чем"},
 {word: "thank", transcription: "[сэнк]", translation: "благодарить"},
 {word: "that", transcription: "[зэт]", translation: "тот, что"},
 {word: "that's", transcription: "[зэтс]", translation: "это, что это"},
 {word: "the", transcription: "[зи]", translation: "определенный артикль"},
 {word: "their", transcription: "дэйр", translate: "их"},
 {word: "them", transcription: "дэм", translate: "их, им"},
 {word: "themselves", transcription: "дэмсэльвз", translate: "сами, себя"},
 {word: "then", transcription: "дэн", translate: "тогда, потом"},
 {word: "there", transcription: "дэр", translate: "там"},
 {word: "there's", transcription: "дэрз", translate: "есть"},
 {word: "these", transcription: "диз", translate: "эти"},
 {word: "they", transcription: "дэй", translate: "они"},
 {word: "they'd", transcription: "дэйд", translate: "они бы"},
 {word: "they're", transcription: "дэйр", translate: "они есть"},
 {word: "thick", transcription: "фик", translate: "толстый"},
 {word: "thing", transcription: "финг", translate: "вещь"},
 {word: "think", transcription: "финк", translate: "думать"},
 {word: "third", transcription: "фёрд", translate: "третий"},
 {word: "this", transcription: "дис", translate: "этот"},
 {word: "those", transcription: "доуз", translate: "те"},
 {word: "though", transcription: "доу", translate: "хотя"},
 {word: "thought", transcription: "фот", translate: "мысль, думать"},
 {word: "three", transcription: "фри", translate: "три"},
 {word: "threw", transcription: "фру", translate: "бросил"},
 {word: "throat", transcription: "фроут", translate: "горло"},
 {word: "through", transcription: "фру", translate: "через"},
 {word: "throw", transcription: "фроу", translate: "бросить"},
 {word: "tie", transcription: "тай", translate: "завязывать"},
 {word: "tight", transcription: "тайт", translate: "плотный"},
 {word: "time", transcription: "тайм", translate: "время"},
 {word: "tiny", transcription: "тайни", translate: "крошечный"},
 {word: "tire", transcription: "тайр", translate: "уставать"},
 {word: "to", transcription: "ту", translate: "к"},
 {word: "today", transcription: "тудэй", translate: "сегодня"},
 {word: "together", transcription: "тугэдзэр", translate: "вместе"},
 {word: "told", transcription: "толд", translate: "сказал"},
 {word: "tomorrow", transcription: "тумороу", translate: "завтра"},
 {word: "tone", transcription: "тон", translate: "тон, оттенок"},
 {word: "tongue", transcription: "танг", translate: "язык"},
 {word: "tonight", transcription: "тунайт", translate: "сегодня вечером"},
 {word: "too", transcription: "ту", translate: "тоже, слишком"},
 {word: "took", transcription: "тук", translate: "взял"},
 {word: "top", transcription: "топ", translate: "верх, верхушка"},
 {word: "totally", transcription: "тотэли", translate: "полностью"},
 {word: "touch", transcription: "тач", translate: "касаться"},
 {word: "toward", transcription: "тоуард", translate: "к, в направлении"},
 {word: "town", transcription: "таун", translate: "город, городок"},
 {word: "track", transcription: "трэк", translate: "трек, след"},
 {word: "trail", transcription: "трэйл", translate: "след, тропа"},
 {word: "train", transcription: "трэйн", translate: "поезд"},
 {word: "tree", transcription: "три", translate: "дерево"},
 {word: "trip", transcription: "трип", translate: "путешествие"},
 {word: "trouble", transcription: "трабл", translate: "проблема"},
 {word: "trust", transcription: "траст", translate: "доверие"},
 {word: "truth", transcription: "труф", translate: "правда"},
 {word: "try", transcription: "трай", translate: "пытаться"},
 {word: "turn", transcription: "тёрн", translate: "поворачивать, поворот"},
 {word: "TV", transcription: "ти-ви", translate: "телевизор"},
 {word: "twenty", transcription: "твэнти", translate: "двадцать"},
 {word: "two", transcription: "ту", translate: "два"},
 {word: "type", transcription: "тайп", translate: "тип, вводить текст"},
 {word: "uncle", transcription: "анкл", translate: "дядя"},
 {word: "under", transcription: "андэр", translate: "под"},
 {word: "understand", transcription: "андэрстэнд", translate: "понимать"},
 {word: "until", transcription: "антил", translate: "до"},
 {word: "up", transcription: "ап", translate: "вверх"},
 {word: "upon", transcription: "апон", translate: "на, по"},
 {word: "us", transcription: "ас", translate: "нас, нам"},
 {word: "use", transcription: "йуз", translate: "использовать"},
 {word: "usual", transcription: "йужуал", translate: "обычный"},
 {word: "usually", transcription: "йужуэли", translate: "обычно"},
 {word: "very", transcription: "вэри", translate: "очень"},
 {word: "visit", transcription: "визит", translate: "посещать"},
 {word: "voice", transcription: "войс", translate: "голос"},
 {word: "wait", transcription: "вэйт", translate: "ждать"},
 {word: "wake", transcription: "вэйк", translate: "просыпаться"},
 {word: "walk", transcription: "уок", translate: "идти, гулять"},
 {word: "wall", transcription: "уол", translate: "стена"},
 {word: "want", transcription: "уонт", translate: "хотеть"},
 {word: "warm", transcription: "уорм", translate: "теплый"},
 {word: "warn", transcription: "уорн", translate: "предупреждать"},
 {word: "was", transcription: "уоз", translate: "был"},
 {word: "wasn't", transcription: "уознт", translate: "не был"},
 {word: "watch", transcription: "уоч", translate: "смотреть, часы"},
 {word: "water", transcription: "уотэр", translate: "вода"},
 {word: "wave", transcription: "вэйв", translate: "волна"},
 {word: "way", transcription: "вэй", translate: "путь, способ"},
 {word: "we", transcription: "уи", translate: "мы"},
 {word: "we'll", transcription: "уил", translate: "мы будем"},
 {word: "we're", transcription: "уир", translate: "мы есть"},
 {word: "we've", transcription: "уив", translate: "у нас есть"},
 {word: "wear", transcription: "уэр", translate: "носить (одежду)"},
 {word: "week", transcription: "уик", translate: "неделя"},
 {word: "weird", transcription: "уирд", translate: "странный"},
 {word: "well", transcription: "уэл", translate: "хорошо"},
 {word: "went", transcription: "уэнт", translate: "пошел"},
 {word: "were", transcription: "уэр", translate: "были"},
 {word: "weren't", transcription: "уэрнт", translate: "не были"},
 {word: "wet", transcription: "уэт", translate: "мокрый"},
 {word: "what", transcription: "уот", translate: "что"},
 {word: "what's", transcription: "уотс", translate: "что это, что такое"},
 {word: "whatever", transcription: "уотэвэр", translate: "что угодно"},
 {word: "when", transcription: "уэн", translate: "когда"},
 {word: "their", transcription: "дэйр", translate: "их"},
 {word: "them", transcription: "дэм", translate: "их, им"},
 {word: "themselves", transcription: "дэмсэльвз", translate: "сами, себя"},
 {word: "then", transcription: "дэн", translate: "тогда, потом"},
 {word: "there", transcription: "дэр", translate: "там"},
 {word: "there's", transcription: "дэрз", translate: "есть"},
 {word: "these", transcription: "диз", translate: "эти"},
 {word: "they", transcription: "дэй", translate: "они"},
 {word: "they'd", transcription: "дэйд", translate: "они бы"},
 {word: "they're", transcription: "дэйр", translate: "они есть"},
 {word: "thick", transcription: "фик", translate: "толстый"},
 {word: "thing", transcription: "финг", translate: "вещь"},
 {word: "think", transcription: "финк", translate: "думать"},
 {word: "third", transcription: "фёрд", translate: "третий"},
 {word: "this", transcription: "дис", translate: "этот"},
 {word: "those", transcription: "доуз", translate: "те"},
 {word: "though", transcription: "доу", translate: "хотя"},
 {word: "thought", transcription: "фот", translate: "мысль, думать"},
 {word: "three", transcription: "фри", translate: "три"},
 {word: "threw", transcription: "фру", translate: "бросил"},
 {word: "throat", transcription: "фроут", translate: "горло"},
 {word: "through", transcription: "фру", translate: "через"},
 {word: "throw", transcription: "фроу", translate: "бросить"},
 {word: "tie", transcription: "тай", translate: "завязывать"},
 {word: "tight", transcription: "тайт", translate: "плотный"},
 {word: "time", transcription: "тайм", translate: "время"},
 {word: "tiny", transcription: "тайни", translate: "крошечный"},
 {word: "tire", transcription: "тайр", translate: "уставать"},
 {word: "to", transcription: "ту", translate: "к"},
 {word: "today", transcription: "тудэй", translate: "сегодня"},
 {word: "together", transcription: "тугэдзэр", translate: "вместе"},
 {word: "told", transcription: "толд", translate: "сказал"},
 {word: "tomorrow", transcription: "тумороу", translate: "завтра"},
 {word: "tone", transcription: "тон", translate: "тон, оттенок"},
 {word: "tongue", transcription: "танг", translate: "язык"},
 {word: "tonight", transcription: "тунайт", translate: "сегодня вечером"},
 {word: "too", transcription: "ту", translate: "тоже, слишком"},
 {word: "took", transcription: "тук", translate: "взял"},
 {word: "top", transcription: "топ", translate: "верх, верхушка"},
 {word: "totally", transcription: "тотэли", translate: "полностью"},
 {word: "touch", transcription: "тач", translate: "касаться"},
 {word: "toward", transcription: "тоуард", translate: "к, в направлении"},
 {word: "town", transcription: "таун", translate: "город, городок"},
 {word: "track", transcription: "трэк", translate: "трек, след"},
 {word: "trail", transcription: "трэйл", translate: "след, тропа"},
 {word: "train", transcription: "трэйн", translate: "поезд"},
 {word: "tree", transcription: "три", translate: "дерево"},
 {word: "trip", transcription: "трип", translate: "путешествие"},
 {word: "trouble", transcription: "трабл", translate: "проблема"},
 {word: "trust", transcription: "траст", translate: "доверие"},
 {word: "truth", transcription: "труф", translate: "правда"},
 {word: "try", transcription: "трай", translate: "пытаться"},
 {word: "turn", transcription: "тёрн", translate: "поворачивать, поворот"},
 {word: "TV", transcription: "ти-ви", translate: "телевизор"},
 {word: "twenty", transcription: "твэнти", translate: "двадцать"},
 {word: "two", transcription: "ту", translate: "два"},
 {word: "type", transcription: "тайп", translate: "тип, вводить текст"},
 {word: "uncle", transcription: "анкл", translate: "дядя"},
 {word: "under", transcription: "андэр", translate: "под"},
 {word: "understand", transcription: "андэрстэнд", translate: "понимать"},
 {word: "until", transcription: "антил", translate: "до"},
 {word: "up", transcription: "ап", translate: "вверх"},
 {word: "upon", transcription: "апон", translate: "на, по"},
 {word: "us", transcription: "ас", translate: "нас, нам"},
 {word: "use", transcription: "йуз", translate: "использовать"},
 {word: "usual", transcription: "йужуал", translate: "обычный"},
 {word: "usually", transcription: "йужуэли", translate: "обычно"},
 {word: "very", transcription: "вэри", translate: "очень"},
 {word: "visit", transcription: "визит", translate: "посещать"},
 {word: "voice", transcription: "войс", translate: "голос"},
 {word: "wait", transcription: "вэйт", translate: "ждать"},
 {word: "wake", transcription: "вэйк", translate: "просыпаться"},
 {word: "walk", transcription: "уок", translate: "идти, гулять"},
 {word: "wall", transcription: "уол", translate: "стена"},
 {word: "want", transcription: "уонт", translate: "хотеть"},
 {word: "warm", transcription: "уорм", translate: "теплый"},
 {word: "warn", transcription: "уорн", translate: "предупреждать"},
 {word: "was", transcription: "уоз", translate: "был"},
 {word: "wasn't", transcription: "уознт", translate: "не был"},
 {word: "watch", transcription: "уоч", translate: "смотреть, часы"},
 {word: "water", transcription: "уотэр", translate: "вода"},
 {word: "wave", transcription: "вэйв", translate: "волна"},
 {word: "way", transcription: "вэй", translate: "путь, способ"},
 {word: "we", transcription: "уи", translate: "мы"},
 {word: "we'll", transcription: "уил", translate: "мы будем"},
 {word: "we're", transcription: "уир", translate: "мы есть"},
 {word: "we've", transcription: "уив", translate: "у нас есть"},
 {word: "wear", transcription: "уэр", translate: "носить (одежду)"},
 {word: "week", transcription: "уик", translate: "неделя"},
 {word: "weird", transcription: "уирд", translate: "странный"},
 {word: "well", transcription: "уэл", translate: "хорошо"},
 {word: "went", transcription: "уэнт", translate: "пошел"},
 {word: "were", transcription: "уэр", translate: "были"},
 {word: "weren't", transcription: "уэрнт", translate: "не были"},
 {word: "wet", transcription: "уэт", translate: "мокрый"},
 {word: "what", transcription: "уот", translate: "что"},
 {word: "what's", transcription: "уотс", translate: "что это, что такое"},
 {word: "whatever", transcription: "уотэвэр", translate: "что угодно"},
 {word: "when", transcription: "уэн", translate: "когда"},
 {word: "where", transcription: "вэр", translate: "где"},
 {word: "whether", transcription: "вэдзэр", translate: "ли, либо"},
 {word: "which", transcription: "вич", translate: "который"},
 {word: "while", transcription: "вайл", translate: "в то время как"},
 {word: "whisper", transcription: "хуиспэр", translate: "шептать"},
 {word: "white", transcription: "хуайт", translate: "белый"},
 {word: "who", transcription: "ху", translate: "кто"},
 {word: "whole", transcription: "хоул", translate: "целый"},
 {word: "why", transcription: "вай", translate: "почему"},
 {word: "wide", transcription: "вайд", translate: "широкий"},
 {word: "wife", transcription: "вайф", translate: "жена"},
 {word: "will", transcription: "вил", translate: "буду, будешь, будет и т.д."},
 {word: "wind", transcription: "уинд", translate: "ветер"},
 {word: "window", transcription: "уиндоу", translate: "окно"},
 {word: "wipe", transcription: "вайп", translate: "вытирать"},
 {word: "wish", transcription: "виш", translate: "желать"},
 {word: "with", transcription: "виз", translate: "с, с помощью"},
 {word: "within", transcription: "видзин", translate: "в пределах, внутри"},
 {word: "without", transcription: "видаут", translate: "без"},
 {word: "woke", transcription: "воук", translate: "пробудился, проснулся"},
 {word: "woman", transcription: "вумэн", translate: "женщина"},
 {word: "women", transcription: "вимэн", translate: "женщины"},
 {word: "won't", transcription: "воунт", translate: "не будет"},
 {word: "wonder", transcription: "вандэр", translate: "удивляться, чудо"},
 {word: "wood", transcription: "вуд", translate: "дерево"},
 {word: "word", transcription: "уёрд", translate: "слово"},
 {word: "wore", transcription: "вор", translate: "носил"},
 {word: "work", transcription: "уёрк", translate: "работа"},
 {word: "world", transcription: "уёрлд", translate: "мир"},
 {word: "worry", transcription: "вари", translate: "беспокоиться"},
 {word: "worse", transcription: "вёрс", translate: "хуже"},
 {word: "would", transcription: "вуд", translate: "бы"},
 {word: "wouldn't", transcription: "вуднт", translate: "не бы"},
 {word: "wow", transcription: "вау", translate: "ух ты"},
 {word: "wrap", transcription: "рэп", translate: "завертывать"},
 {word: "write", transcription: "райт", translate: "писать"},
 {word: "wrong", transcription: "ронг", translate: "неправильный"},
 {word: "yeah", transcription: "йе", translate: "да"},
 {word: "year", transcription: "йир", translate: "год"},
 {word: "yell", transcription: "йэл", translate: "кричать"},
 {word: "yes", transcription: "йэс", translate: "да"},
 {word: "yet", transcription: "йэт", translate: "еще, уже"},
 {word: "you", transcription: "йу", translate: "ты, вы"},
 {word: "you'd", transcription: "йуд", translate: "ты бы"},
 {word: "you'll", transcription: "йул", translate: "ты будешь"},
 {word: "you're", transcription: "йор", translate: "ты есть"},
 {word: "you've", transcription: "йув", translate: "у тебя есть"},
 {word: "young", transcription: "йанг", translate: "молодой"},
 {word: "your", transcription: "йор", translate: "твой, ваш"},
 {word: "yourself", transcription: "йорсэлф", translate: "себя"}
]


# def make_transcription(word)
#   vowels = %w[a e i o u]
#   consonants = %w[b c d f g h j k l m n p q r s t v w x y z]
#   transcription = ""

#   word.downcase.chars.each_with_index do |char, index|
#     if vowels.include?(char)
#       case char
#       when "a"
#         if index.zero? || consonants.include?(word[index - 1])
#           transcription += "[э]"
#         elsif word[index + 1] == "r"
#           transcription += "[а]"
#         else
#           transcription += "[э]"
#         end
#       when "e"
#         if index.zero? || consonants.include?(word[index - 1])
#           transcription += "[э]"
#         elsif word[index + 1] == "r"
#           transcription += "[э]"
#         else
#           transcription += "[и]"
#         end
#       when "i"
#         if index.zero? || consonants.include?(word[index - 1])
#           transcription += "[ай]"
#         else
#           transcription += "[и]"
#         end
#       when "o"
#         transcription += "[о]"
#       when "u"
#         if index.zero? || consonants.include?(word[index - 1])
#           transcription += "[а]"
#         else
#           transcription += "[у]"
#         end
#       end
#     elsif consonants.include?(char)
#       case char
#       when "c"
#         transcription += word[index + 1] == "h" ? "[ч]" : "[к]"
#       when "g"
#         if word[index + 1] == "h"
#           transcription += "[г]"
#         elsif vowels.include?(word[index + 1])
#           transcription += "[г]"
#         else
#           transcription += "[г]"
#         end
#       when "h"
#         if index == 0 || consonants.include?(word[index - 1])
#           transcription += "[х]"
#         else
#           transcription += ""
#         end
#       when "j"
#         transcription += "[дж]"
#       when "q"
#         transcription += "[кв]"
#       when "r"
#         transcription += "[р]"
#       when "s"
#         transcription += word[index + 1] == "h" ? "[ш]" : "[с]"
#       when "t"
#         if word[index + 1] == "h"
#           transcription += "[з]"
#         elsif index == word.length - 1 || consonants.include?(word[index + 1])
#           transcription += "[т]"
#         else
#           transcription += "[т]"
#         end
#       when "x"
#         transcription += "[кс]"
#       when "y"
#         if vowels.include?(word[index + 1])
#           transcription += "[й]"
#         elsif index.zero? || consonants.include?(word[index - 1])
#           transcription += "[й]"
#         else
#           transcription += "[ай]"
#         end
#       when "z"
#         transcription += "[з]"
#       else
#         transcription += "[#{char}]"
#       end
#     else
#       transcription += char
#     end
#   end

#   transcription
# end

# word = "Hello"
# transcription = make_transcription(word)
# puts "#{word}: #{transcription}"

words.each do |data|
  Word.find_or_create_by(word: data[:word]) do |word|
    word.translation = data[:translate] || data[:translation]
    word.transcription = data[:transcription]
  end
end
