require_relative '../lib/app_config'
require_relative '../models/word'

db = AppConfig.instance.db

words = [
  {word: "a", transcription: "[эй]", translate: "определенный артикль, один из"},
  {word: "able", transcription: "[эйбл]", translate: "способный, могущий"},
  {word: "about", transcription: "[əˈбаут]", translate: "о, около"},
  {word: "above", transcription: "[əˈбʌв]", translate: "над, выше"},
  {word: "accept", transcription: "[əкˈсэпт]", translate: "принимать, соглашаться"},
  {word: "across", transcription: "[əˈкрос]", translate: "через, поперек"},
  {word: "act", transcription: "[экт]", translate: "действовать, поступать"},
  {word: "actually", transcription: "[ˈэкчуэли]", translate: "фактически, в самом деле"},
  {word: "add", transcription: "[эд]", translate: "добавлять, прибавлять"},
  {word: "admit", transcription: "[əдˈмит]", translate: "признавать, допускать"},
  {word: "afraid", transcription: "[əˈфрейд]", translate: "испуганный, боящийся"},
  {word: "after", transcription: "[ˈафтə]", translate: "после"},
  {word: "afternoon", transcription: "[ˌɑːftəˈнуːн]", translate: "после полудня, день"},
  {word: "again", transcription: "[əˈген]", translate: "снова, опять"},
  {word: "against", transcription: "[əˈгэнст]", translate: "против"},
  {word: "age", transcription: "[ейдж]", translate: "возраст"},
  {word: "ago", transcription: "[əˈгоу]", translate: "назад, давно"},
  {word: "agree", transcription: "[əˈгриː]", translate: "соглашаться"},
  {word: "ah", transcription: "[аː]", translate: "ах, о"},
  {word: "ahead", transcription: "[əˈхед]", translate: "вперед, впереди"},
  {word: "air", transcription: "[еə]", translate: "воздух"},
  {word: "all", transcription: "[оːл]", translate: "все"},
  {word: "allow", transcription: "[əˈлау]", translate: "позволять"},
  {word: "almost", transcription: "[ˈолмоуст]", translate: "почти"},
  {word: "alone", transcription: "[əˈлоун]", translate: "один, в одиночестве"},
  {word: "along", transcription: "[əˈлоːн]", translate: "вдоль"},
  {word: "already", transcription: "[ɔːˈлреди]", translate: "уже"},
  {word: "alright", transcription: "[ɔːˈлрайт]", translate: "хорошо"},
  {word: "also", transcription: "[ˈольсоу]", translate: "также"},
  {word: "although", transcription: "[ɔːlˈðоу]", translate: "хотя"},
  {word: "always", transcription: "[ˈольвэйз]", translate: "всегда"},
  {word: "am", transcription: "[эм]", translate: "являюсь"},
  {word: "amaze", transcription: "[əˈмейз]", translate: "удивлять"},
  {word: "an", transcription: "[эн]", translate: "неопределенный артикль"},
  {word: "and", transcription: "[энд]", translate: "и"},
  {word: "anger", transcription: "[ˈэнгə]", translate: "гнев"},
  {word: "angry", transcription: "[ˈэнгри]", translate: "злой"},
  {word: "animal", transcription: "[ˈэнимэл]", translate: "животное"},
  {word: "annoy", transcription: "[эˈной]", translate: "раздражать"},
  {word: "another", transcription: "[əˈназə]", translate: "другой"},
  {word: "answer", transcription: "[ˈэнсə]", translate: "ответ"},
  {word: "any", transcription: "[эни]", translate: "любой"},
  {word: "anymore", transcription: "[эниˈмоː]", translate: "больше не"},
  {word: "anyone", transcription: "[ˈэниван]", translate: "кто-то"},
  {word: "anything", transcription: "[ˈэниθинг]", translate: "что-то"},
  {word: "anyway", transcription: "[ˈэнивэй]", translate: "в любом случае"},
  {word: "apartment", transcription: "[əˈпартмəнт]", translate: "квартира"},
  {word: "apparently", transcription: "[əˈпэрəнтли]", translate: "очевидно"},
  {word: "appear", transcription: "[əˈпиə]", translate: "появляться"},
  {word: "approach", transcription: "[əˈпроуч]", translate: "подходить"},
  {word: "are", transcription: "[ар]", translate: "быть, являться (форма глагола)"},
  {word: "area", transcription: "[эриа]", translate: "область, район"},
  {word: "aren't", transcription: "[арнт]", translate: "не быть (сокращенная форма)"},
  {word: "arm", transcription: "[арм]", translate: "рука"},
  {word: "around", transcription: "[эраунд]", translate: "вокруг"},
  {word: "arrive", transcription: "[аррайв]", translate: "прибывать"},
  {word: "as", transcription: "[эз]", translate: "как, в то время как"},
  {word: "ask", transcription: "[аск]", translate: "спрашивать"},
  {word: "asleep", transcription: "[аслип]", translate: "спящий, спит"},
  {word: "ass", transcription: "[эс]", translate: "жопа"},
  {word: "at", transcription: "[эт]", translate: "у, в, на"},
  {word: "attack", transcription: "[эттэк]", translate: "атаковать"},
  {word: "attempt", transcription: "[эттемпт]", translate: "попытка"},
  {word: "attention", transcription: "[этеншн]", translate: "внимание"},
  {word: "aunt", transcription: "[онт]", translate: "тётя"},
  {word: "avoid", transcription: "[эвойд]", translate: "избегать"},
  {word: "away", transcription: "[эвэй]", translate: "далеко"},
  {word: "baby", transcription: "[бейби]", translate: "младенец, ребенок"},
  {word: "back", transcription: "[бэк]", translate: "спина, назад"},
  {word: "bad", transcription: "[бэд]", translate: "плохой"},
  {word: "bag", transcription: "[бэг]", translate: "сумка"},
  {word: "ball", transcription: "[бол]", translate: "мяч"},
  {word: "band", transcription: "[бэнд]", translate: "группа, бандa"},
  {word: "bar", transcription: "[бар]", translate: "полоса, бар"},
  {word: "barely", transcription: "[бэрли]", translate: "едва ли"},
  {word: "bathroom", transcription: "[бэсрум]", translate: "ванная комната"},
  {word: "be", transcription: "[би]", translate: "быть, являться (форма глагола)"},
  {word: "beat", transcription: "[бит]", translate: "победить, ударить"},
  {word: "beautiful", transcription: "[бьютифул]", translate: "красивый"},
  {word: "became", transcription: "[бикейм]", translate: "стал, стала (прошедшее время от become)"},
  {word: "because", transcription: "[бикоз]", translate: "потому что"},
  {word: "become", transcription: "[бикам]", translate: "становиться"},
  {word: "bed", transcription: "[бед]", translate: "кровать"},
  {word: "bedroom", transcription: "[бедрум]", translate: "спальня"},
  {word: "been", transcription: "[бин]", translate: "был, была (прошедшее время от be)"},
  {word: "before", transcription: "[бифор]", translate: "перед, до"},
  {word: "began", transcription: "[бигэн]", translate: "начал (прошедшее время от begin)"},
  {word: "begin", transcription: "[бигин]", translate: "начинать"},
  {word: "behind", transcription: "[бихайнд]", translate: "позади, за"},
  {word: "believe", transcription: "[билййв]", translate: "верить"},
  {word: "bell", transcription: "[бел]", translate: "колокол"},
  {word: "beside", transcription: "[бизайд]", translate: "рядом"},
  {word: "besides", transcription: "[бизайдз]", translate: "кроме, помимо"},
  {word: "best", transcription: "[бест]", translate: "лучший"},
  {word: "better", transcription: "[бетэр]", translate: "лучше"},
  {word: "between", transcription: "[битвин]", translate: "между"},
  {word: "big", transcription: "[биг]", translate: "большой"},
  {word: "bit", transcription: "[бит]", translate: "немного"},
  {word: "bite", transcription: "[байт]", translate: "кусать"},
  {word: "black", transcription: "[блэк]", translate: "черный"},
  {word: "blink", transcription: "[блинк]", translate: "мигать"},
  {word: "block", transcription: "[блок]", translate: "блокировать"},
  {word: "blonde", transcription: "[блонд]", translate: "блондин(ка)"},
  {word: "blood", transcription: "[блуд]", translate: "кровь"},
  {word: "blue", transcription: "[блу]", translate: "синий"},
  {word: "blush", transcription: "[блаш]", translate: "румянец, краснеть"},
  {word: "body", transcription: "[боди]", translate: "тело"},
  {word: "book", transcription: "[бук]", translate: "книга"},
  {word: "bore", transcription: "[бор]", translate: "скучный"},
  {word: "both", transcription: "[боуз]", translate: "оба"},
  {word: "bother", transcription: "[бадер]", translate: "беспокоить"},
  {word: "bottle", transcription: "[ботл]", translate: "бутылка"},
  {word: "bottom", transcription: "[ботам]", translate: "нижняя часть"},
  {word: "box", transcription: "[бокс]", translate: "коробка, ящик"},
  {word: "boy", transcription: "[бой]", translate: "мальчик"},
  {word: "boyfriend", transcription: "[бойфрэнд]", translate: "бойфренд"},
  {word: "brain", transcription: "[брейн]", translate: "мозг"},
  {word: "break", transcription: "[брейк]", translate: "перерыв, разрушать"},
  {word: "breakfast", transcription: "[брекфест]", translate: "завтрак"},
  {word: "breath", transcription: "[брет]", translate: "дыхание"},
  {word: "breathe", transcription: "[бридз]", translate: "дышать"},
  {word: "bright", transcription: "[брайт]", translate: "яркий"},
  {word: "bring", transcription: "[бринг]", translate: "приносить"},
  {word: "broke", transcription: "[брок]", translate: "разбитый, сломанный (прошедшее время от break)"},
  {word: "broken", transcription: "[брокен]", translate: "разбитый, сломанный"},
  {word: "brother", transcription: "[бразер]", translate: "брат"},
  {word: "brought", transcription: "[брот]", translate: "принес (прошедшее время от bring)"},
  {word: "brown", transcription: "[браун]", translate: "коричневый"},
  {word: "brush", transcription: "[браш]", translate: "щетка"},
  {word: "build", transcription: "[билд]", translate: "строить"},
  {word: "burn", transcription: "[бён]", translate: "гореть"},
  {word: "burst", transcription: "[бёрст]", translate: "взрыв, взрываться"},
  {word: "bus", transcription: "[бас]", translate: "автобус"},
  {word: "business", transcription: "[бизнес]", translate: "бизнес"},
  {word: "busy", transcription: "[бизи]", translate: "занятой"},
  {word: "but", transcription: "[бат]", translate: "но"},
  {word: "buy", transcription: "[бай]", translate: "покупать"},
  {word: "by", transcription: "[бай]", translate: "по, от"},
  {word: "call", transcription: "[кол]", translate: "звонить, называть"},
  {word: "calm", transcription: "[кам]", translate: "спокойный"},
  {word: "came", transcription: "[кейм]", translate: "пришел, пришла (прошедшее время от come)"},
  {word: "can", transcription: "[кен]", translate: "мочь, уметь"},
  {word: "can't", transcription: "[кант]", translate: "не мочь, не уметь"},
  {word: "car", transcription: "[кар]", translate: "машина"},
  {word: "card", transcription: "[кард]", translate: "карта"},
  {word: "care", transcription: "[кер]", translate: "забота, ухаживать"},
  {word: "carefully", transcription: "[кэрфули]", translate: "осторожно"},
  {word: "carry", transcription: "[кэри]", translate: "нести, нести"},
  {word: "case", transcription: "[кейс]", translate: "случай, ящик"},
  {word: "cat", transcription: "[кэт]", translate: "кот"},
  {word: "catch", transcription: "[кэч]", translate: "ловить, поймать"},
  {word: "caught", transcription: "[кот]", translate: "пойманный"},
  {word: "cause", transcription: "[коз]", translate: "причина, вызывать"},
  {word: "cell", transcription: "[сел]", translate: "ячейка, клетка"},
  {word: "chair", transcription: "[чээр]", translate: "стул"},
  {word: "chance", transcription: "[чэнс]", translate: "шанс, случай"},
  {word: "change", transcription: "[чейндж]", translate: "изменение, менять"},
  {word: "chase", transcription: "[чейс]", translate: "погоня, гнаться"},
  {word: "check", transcription: "[чек]", translate: "проверка, проверять"},
  {word: "cheek", transcription: "[чик]", translate: "щека"},
  {word: "chest", transcription: "[чест]", translate: "грудь, сундук"},
  {word: "child", transcription: "[чайлд]", translate: "ребенок"},
  {word: "children", transcription: "[чилдрэн]", translate: "дети"},
  {word: "chuckle", transcription: "[чакл]", translate: "хихикать"},
  {word: "city", transcription: "[сити]", translate: "город"},
  {word: "class", transcription: "[клас]", translate: "класс"},
  {word: "clean", transcription: "[клиːн]", translate: "чистый, убирать"},
  {word: "clear", transcription: "[клиə]", translate: "чистый, ясный"},
  {word: "climb", transcription: "[клайм]", translate: "взбираться"},
  {word: "close", transcription: "[клоуз]", translate: "близкий, закрывать"},
  {word: "clothes", transcription: "[клоуðз]", translate: "одежда"},
  {word: "coffee", transcription: "[кофи]", translate: "кофе"},
  {word: "cold", transcription: "[коулд]", translate: "холодный"},
  {word: "college", transcription: "[колледж]", translate: "колледж"},
  {word: "color", transcription: "[колор]", translate: "цвет"},
  {word: "come", transcription: "[кам]", translate: "приходить"},
  {word: "comment", transcription: "[коммент]", translate: "комментарий"},
  {word: "complete", transcription: "[комплит]", translate: "полный, завершать"},
  {word: "completely", transcription: "[комплитли]", translate: "полностью"},
  {word: "computer", transcription: "[компьютер]", translate: "компьютер"},
  {word: "concern", transcription: "[консерн]", translate: "беспокойство, касаться"},
  {word: "confuse", transcription: "[конфьюз]", translate: "путать, смущать"},
  {word: "consider", transcription: "[консидер]", translate: "рассматривать, считать"},
  {word: "continue", transcription: "[континью]", translate: "продолжать"},
  {word: "control", transcription: "[контроул]", translate: "контроль, управлять"},
  {word: "conversation", transcription: "[конвёрсейшн]", translate: "разговор"},
  {word: "cool", transcription: "[кул]", translate: "прохладный, клевый"},
  {word: "corner", transcription: "[корнэр]", translate: "угол"},
  {word: "couch", transcription: "[кауч]", translate: "диван"},
  {word: "could", transcription: "[куд]", translate: "мог, могли"},
  {word: "couldn't", transcription: "[куднт]", translate: "не мог, не могли"},
  {word: "counter", transcription: "[каунтер]", translate: "прилавок, счетчик"},
  {word: "couple", transcription: "[капл]", translate: "пара, несколько"},
  {word: "course", transcription: "[корс]", translate: "курс, ход"},
  {word: "cover", transcription: "[кавер]", translate: "покрытие, накрывать"},
  {word: "crack", transcription: "[крек]", translate: "треск, трещина"},
  {word: "crazy", transcription: "[крейзи]", translate: "сумасшедший"},
  {word: "cross", transcription: "[кросс]", translate: "пересекать"},
  {word: "crowd", transcription: "[крауд]", translate: "толпа, народ"},
  {word: "cry", transcription: "[край]", translate: "плакать, кричать"},
  {word: "cup", transcription: "[кап]", translate: "чашка"},
  {word: "cut", transcription: "[кат]", translate: "резать"},
  {word: "cute", transcription: "[кьют]", translate: "милый, симпатичный"},
  {word: "dad", transcription: "[дэд]", translate: "папа"},
  {word: "damn", transcription: "[дэм]", translate: "проклятие, черт"},
  {word: "dance", transcription: "[данс]", translate: "танцевать"},
  {word: "dark", transcription: "[дарк]", translate: "темный"},
  {word: "date", transcription: "[дейт]", translate: "свидание"},
  {word: "daughter", transcription: "[дотэр]", translate: "дочь"},
  {word: "day", transcription: "[дей]", translate: "день"},
  {word: "dead", transcription: "[дэд]", translate: "мертвый"},
  {word: "deal", transcription: "[дил]", translate: "сделка, соглашение"},
  {word: "dear", transcription: "[дир]", translate: "дорогой, любимый"},
  {word: "death", transcription: "[дэс]", translate: "смерть"},
  {word: "decide", transcription: "[дисайд]", translate: "решить"},
  {word: "deep", transcription: "[дип]", translate: "глубокий"},
  {word: "definitely", transcription: "[дефинитли]", translate: "определенно"},
  {word: "desk", transcription: "[деск]", translate: "письменный стол, стол"},
  {word: "did", transcription: "[дид]", translate: "делал"},
  {word: "didn't", transcription: "[диднт]", translate: "не делал"},
  {word: "die", transcription: "[дай]", translate: "умирать"},
  {word: "different", transcription: "[дифэрэнт]", translate: "разный, различный"},
  {word: "dinner", transcription: "[диннэр]", translate: "ужин"},
  {word: "direction", transcription: "[дирекшн]", translate: "направление"},
  {word: "disappear", transcription: "[дисэпиэр]", translate: "исчезать"},
  {word: "do", transcription: "[ду]", translate: "делать"},
  {word: "doctor", transcription: "[доктэр]", translate: "врач"},
  {word: "does", transcription: "[даз]", translate: "делает"},
  {word: "doesn't", transcription: "[дазнт]", translate: "не делает"},
  {word: "dog", transcription: "[дог]", translate: "собака"},
  {word: "don't", transcription: "[доунт]", translate: "не делай, не делать"},
  {word: "done", transcription: "[дан]", translate: "сделано"},
  {word: "door", transcription: "[дор]", translate: "дверь"},
  {word: "doubt", transcription: "[даут]", translate: "сомнение"},
  {word: "down", transcription: "[даун]", translate: "вниз, внизу"},
  {word: "drag", transcription: "[драг]", translate: "тащить"},
  {word: "draw", transcription: "[дро]", translate: "рисовать"},
  {word: "dream", transcription: "[дрим]", translate: "сон, мечта"},
  {word: "dress", transcription: "[дрес]", translate: "платье, одеваться"},
  {word: "drink", transcription: "[дринк]", translate: "пить"},
  {word: "drive", transcription: "[драйв]", translate: "вести машину, водить"},
  {word: "drop", transcription: "[дроп]", translate: "падать, капля"},
  {word: "drove", transcription: "[дроув]", translate: "вел, ехал (о транспортном средстве)"},
  {word: "dry", transcription: "[драй]", translate: "сухой, сушить"},
  {word: "during", transcription: "[дюринг]", translate: "в течение, во время"},
  {word: "each", transcription: "[ич]", translate: "каждый"},
  {word: "ear", transcription: "[иэр]", translate: "ухо"},
  {word: "early", transcription: "[ёрли]", translate: "рано"},
  {word: "easily", transcription: "[изли]", translate: "легко"},
  {word: "easy", transcription: "[изи]", translate: "легкий, простой"},
  {word: "eat", transcription: "[ит]", translate: "есть"},
  {word: "edge", transcription: "[эдж]", translate: "край"},
  {word: "either", transcription: "[айзэр]", translate: "любой из двух, также"},
  {word: "else", transcription: "[элс]", translate: "еще, кроме того"},
  {word: "empty", transcription: "[эмпти]", translate: "пустой"},
  {word: "end", transcription: "[энд]", translate: "конец, заканчивать"},
  {word: "enjoy", transcription: "[инджой]", translate: "наслаждаться"},
  {word: "enough", transcription: "[инаф]", translate: "достаточно"},
  {word: "enter", transcription: "[энтэр]", translate: "войти, входить"},
  {word: "entire", transcription: "[энтайр]", translate: "весь, целый"},
  {word: "escape", transcription: "[искейп]", translate: "избежать, сбежать"},
  {word: "especially", transcription: "[испешли]", translate: "особенно"},
  {word: "even", transcription: "[ивэн]", translate: "даже"},
  {word: "evening", transcription: "[ивнин]", translate: "вечер"},
  {word: "eventually", transcription: "[ивентюли]", translate: "в конечном итоге"},
  {word: "ever", transcription: "[эвэр]", translate: "когда-либо"},
  {word: "every", transcription: "[эври]", translate: "каждый"},
  {word: "everyone", transcription: "[эвриван]", translate: "каждый, все"},
  {word: "everything", transcription: "[эврисинг]", translate: "все"},
  {word: "exactly", transcription: "[игзэктли]", translate: "точно, именно"},
  {word: "except", transcription: "[иксепт]", translate: "кроме"},
  {word: "excite", transcription: "[иксайт]", translate: "возбуждать"},
  {word: "exclaim", transcription: "[иксклейм]", translate: "восклицать"},
  {word: "excuse", transcription: "[икскьюз]", translate: "извинение, извинить"},
  {word: "expect", transcription: "[икспект]", translate: "ожидать"},
  {word: "explain", transcription: "[иксплейн]", translate: "объяснять"},
  {word: "expression", transcription: "[икспрешн]", translate: "выражение"},
  {word: "eye", transcription: "[ай]", translate: "глаз"},
  {word: "eyebrow", transcription: "[айброу]", translate: "бровь"},
  {word: "face", transcription: "[фейс]", translate: "лицо, сталкиваться"},
  {word: "fact", transcription: "[фэкт]", translate: "факт"},
  {word: "fall", transcription: "[фол]", translate: "падать, осень"},
  {word: "family", transcription: "[фэмли]", translate: "семья"},
  {word: "far", transcription: "[фар]", translate: "далеко"},
  {word: "fast", transcription: "[фаст]", translate: "быстро, поститься"},
  {word: "father", transcription: "[фазэр]", translate: "отец"},
  {word: "fault", transcription: "[фолт]", translate: "вина, ошибка"},
  {word: "favorite", transcription: "[фэйвэрит]", translate: "любимый"},
  {word: "fear", transcription: "[фир]", translate: "страх"},
  {word: "feel", transcription: "[фил]", translate: "чувствовать"},
  {word: "feet", transcription: "[фит]", translate: "ноги"},
  {word: "fell", transcription: "[фел]", translate: "упал"},
  {word: "felt", transcription: "[фелт]", translate: "чувствовал"},
  {word: "few", transcription: "[фью]", translate: "несколько"},
  {word: "field", transcription: "[филд]", translate: "поле"},
  {word: "fight", transcription: "[файт]", translate: "драка, борьба"},
  {word: "figure", transcription: "[фигёр]", translate: "фигура, образ"},
  {word: "fill", transcription: "[фил]", translate: "заполнять"},
  {word: "finally", transcription: "[файнли]", translate: "наконец"},
  {word: "find", transcription: "[файнд]", translate: "находить"},
  {word: "fine", transcription: "[файн]", translate: "хорошо, отлично"},
  {word: "finger", transcription: "[финггэр]", translate: "палец"},
  {word: "finish", transcription: "[финиш]", translate: "заканчивать"},
  {word: "fire", transcription: "[файр]", translate: "огонь"},
  {word: "first", transcription: "[фёрст]", translate: "первый"},
  {word: "fit", transcription: "[фит]", translate: "подходить, соответствовать"},
  {word: "five", transcription: "[файв]", translate: "пять"},
  {word: "fix", transcription: "[фикс]", translate: "чинить, фиксировать"},
  {word: "flash", transcription: "[флэш]", translate: "вспышка, сверкать"},
  {word: "flip", transcription: "[флип]", translate: "переворачивать"},
  {word: "floor", transcription: "[флор]", translate: "пол, этаж"},
  {word: "fly", transcription: "[флай]", translate: "летать"},
  {word: "focus", transcription: "[фоукас]", translate: "фокусироваться"},
  {word: "follow", transcription: "[фолоу]", translate: "следовать, следить"},
  {word: "food", transcription: "[фуд]", translate: "еда"},
  {word: "foot", transcription: "[фут]", translate: "нога, ступня"},
  {word: "for", transcription: "[фо]", translate: "для, за"},
  {word: "force", transcription: "[форс]", translate: "сила, заставлять"},
  {word: "forget", transcription: "[форгет]", translate: "забывать"},
  {word: "form", transcription: "[форм]", translate: "форма, создавать"},
  {word: "forward", transcription: "[форвард]", translate: "вперед"},
  {word: "found", transcription: "[фаунд]", translate: "находить, основывать"},
  {word: "four", transcription: "[фо]", translate: "четыре"},
  {word: "free", transcription: "[фри]", translate: "свободный, бесплатный"},
  {word: "friend", transcription: "[френд]", translate: "друг"},
  {word: "from", transcription: "[фром]", translate: "из, от"},
  {word: "front", transcription: "[фронт]", translate: "перед"},
  {word: "frown", transcription: "[фраун]", translate: "нахмуриваться"},
  {word: "fuck", transcription: "[фак]", translate: "переспать, трахнуть"},
  {word: "full", transcription: "[фул]", translate: "полный"},
  {word: "fun", transcription: "[фан]", translate: "веселье"},
  {word: "funny", transcription: "[фанни]", translate: "смешной"},
  {word: "further", transcription: "[фёрдер]", translate: "дальше"},
  {word: "game", transcription: "[гейм]", translate: "игра"},
  {word: "gasp", transcription: "[гэсп]", translate: "вздохнуть"},
  {word: "gave", transcription: "[гэйв]", translate: "дал, отдавал"},
  {word: "gaze", transcription: "[гейз]", translate: "взгляд"},
  {word: "gently", transcription: "[джентли]", translate: "мягко"},
  {word: "get", transcription: "[гет]", translate: "получать, доставать"},
  {word: "giggle", transcription: "[гигл]", translate: "хихикать"},
  {word: "girl", transcription: "[гёрл]", translate: "девушка"},
  {word: "girlfriend", transcription: "[гёрлфренд]", translate: "подруга, девушка"},
  {word: "give", transcription: "[гив]", translate: "давать"},
  {word: "given", transcription: "[гивэн]", translate: "данный"},
  {word: "glad", transcription: "[глэд]", translate: "рад"},
  {word: "glance", transcription: "[гланс]", translate: "взгляд"},
  {word: "glare", transcription: "[глэр]", translate: "ярко светить, сердитый взгляд"},
  {word: "glass", transcription: "[глас]", translate: "стекло, бокал"},
  {word: "go", transcription: "[гоу]", translate: "идти, ехать"},
  {word: "God", transcription: "[год]", translate: "Бог"},
  {word: "gone", transcription: "[гон]", translate: "ушел, ушедший"},
  {word: "gonna", transcription: "[гана]", translate: "собирается, намеревается"},
  {word: "good", transcription: "[гуд]", translate: "хороший, добрый"},
  {word: "got", transcription: "[гот]", translate: "получил, имел"},
  {word: "gotten", transcription: "[готн]", translate: "полученный"},
  {word: "grab", transcription: "[грэб]", translate: "хватать"},
  {word: "great", transcription: "[грейт]", translate: "великолепный, отличный"},
  {word: "green", transcription: "[грин]", translate: "зеленый"},
  {word: "greet", transcription: "[грит]", translate: "приветствовать"},
  {word: "grey", transcription: "[грей]", translate: "серый"},
  {word: "grin", transcription: "[грин]", translate: "ухмыляться"},
  {word: "grip", transcription: "[грип]", translate: "захват, сцепление"},
  {word: "groan", transcription: "[гроун]", translate: "стон, стонать"},
  {word: "ground", transcription: "[граунд]", translate: "земля, основание"},
  {word: "group", transcription: "[груп]", translate: "группа"},
  {word: "grow", transcription: "[гроу]", translate: "расти"},
  {word: "guard", transcription: "[гард]", translate: "сторожить, охранять"},
  {word: "guess", transcription: "[гесс]", translate: "угадывать, догадываться"},
  {word: "gun", transcription: "[ган]", translate: "пистолет, оружие"},
  {word: "guy", transcription: "[гай]", translate: "парень, человек"},
  {word: "had", transcription: "[хэд]", translate: "имел"},
  {word: "hadn't", transcription: "[хэднт]", translate: "не имел"},
  {word: "hair", transcription: "[хер]", translate: "волосы"},
  {word: "half", transcription: "[хаф]", translate: "половина"},
  {word: "hall", transcription: "[хол]", translate: "зал, коридор"},
  {word: "hallway", transcription: "[холвэй]", translate: "коридор"},
  {word: "hand", transcription: "[хэнд]", translate: "рука"},
  {word: "handle", transcription: "[хэндл]", translate: "ручка, обращаться"},
  {word: "hang", transcription: "[хэнг]", translate: "висеть, вешать"},
  {word: "happen", transcription: "[хэпэн]", translate: "случаться"},
  {word: "happy", transcription: "[хэппи]", translate: "счастливый"},
  {word: "hard", transcription: "[хард]", translate: "трудный, жесткий"},
  {word: "has", transcription: "[хэз]", translate: "имеет"},
  {word: "hate", transcription: "[хейт]", translate: "ненавидеть"},
  {word: "have", transcription: "[хэв]", translate: "иметь"},
  {word: "haven't", transcription: "[хэвнт]", translate: "не имеет"},
  {word: "he", transcription: "[хи]", translate: "он"},
  {word: "he'd", transcription: "[хид]", translate: "он бы"},
  {word: "he's", transcription: "[хиз]", translate: "он есть, он имеет"},
  {word: "head", transcription: "[хед]", translate: "голова"},
  {word: "hear", transcription: "[хир]", translate: "слышать"},
  {word: "heard", transcription: "[хёрд]", translate: "слышал"},
  {word: "heart", transcription: "[харт]", translate: "сердце"},
  {word: "heavy", transcription: "[хеви]", translate: "тяжелый"},
  {word: "held", transcription: "[хэлд]", translate: "держал"},
  {word: "hell", transcription: "[хел]", translate: "ад"},
  {word: "hello", transcription: "[хэллоу]", translate: "привет"},
  {word: "help", transcription: "[хэлп]", translate: "помощь, помогать"},
  {word: "her", transcription: "[хёр]", translate: "ее, ей"},
  {word: "here", transcription: "[хир]", translate: "здесь"},
  {word: "herself", transcription: "[хёрсэлф]", translate: "себя, сама"},
  {word: "hey", transcription: "[хей]", translate: "привет"},
  {word: "hi", transcription: "[хай]", translate: "привет"},
  {word: "hide", transcription: "[хайд]", translate: "прятаться, скрывать"},
  {word: "high", transcription: "[хай]", translate: "высокий"},
  {word: "him", transcription: "[хим]", translate: "его, ему"},
  {word: "himself", transcription: "[химсэлф]", translate: "себя, сам"},
  {word: "his", transcription: "[хиз]", translate: "его"},
  {word: "hit", transcription: "[хит]", translate: "удар, ударять"},
  {word: "hold", transcription: "[холд]", translate: "держать"},
  {word: "home", transcription: "[хоум]", translate: "дом"},
  {word: "hope", transcription: "[хоуп]", translate: "надежда, надеяться"},
  {word: "horse", transcription: "[хорс]", translate: "лошадь"},
  {word: "hospital", transcription: "[хоспитл]", translate: "больница"},
  {word: "hot", transcription: "[хот]", translate: "горячий, жарко"},
  {word: "hour", transcription: "[ауэр]", translate: "час"},
  {word: "house", transcription: "[хаус]", translate: "дом"},
  {word: "how", transcription: "[хау]", translate: "как, каким образом"},
  {word: "however", transcription: "[хауэвэр]", translate: "однако, тем не менее"},
  {word: "hug", transcription: "[хаг]", translate: "обнимать"},
  {word: "huge", transcription: "[хьюдж]", translate: "огромный"},
  {word: "huh", transcription: "[ха]", translate: "эй, эй ты"},
  {word: "human", transcription: "[хьюмэн]", translate: "человек"},
  {word: "hundred", transcription: "[хандрэд]", translate: "сто"},
  {word: "hung", transcription: "[ханг]", translate: "висел, висящий"},
  {word: "hurry", transcription: "[хёри]", translate: "торопиться, спешить"},
  {word: "hurt", transcription: "[хёрт]", translate: "причинять боль, больно"},
  {word: "I", transcription: "[ай]", translate: "я"},
  {word: "I'd", transcription: "[айд]", translate: "я бы"},
  {word: "I'll", transcription: "[айл]", translate: "я буду"},
  {word: "I'm", transcription: "[айм]", translate: "я есть, я нахожусь"},
  {word: "I've", transcription: "[айв]", translate: "у меня есть"},
  {word: "ice", transcription: "[айс]", translate: "лед"},
  {word: "idea", transcription: "[айдиа]", translate: "идея, понятие"},
  {word: "if", transcription: "[иф]", translate: "если"},
  {word: "ignore", transcription: "[игнор]", translate: "игнорировать"},
  {word: "imagine", transcription: "[имэджин]", translate: "воображать"},
  {word: "immediately", transcription: "[имидиэтли]", translate: "немедленно"},
  {word: "important", transcription: "[импортэнт]", translate: "важный"},
  {word: "in", transcription: "[ин]", translate: "в, на"},
  {word: "inside", transcription: "[инсайд]", translate: "внутри"},
  {word: "instead", transcription: "[инстед]", translate: "вместо"},
  {word: "interest", transcription: "[интерэст]", translate: "интерес, интересовать"},
  {word: "interrupt", transcription: "[интэрапт]", translate: "перебивать, прерывать"},
  {word: "into", transcription: "[инту]", translate: "в, внутрь"},
  {word: "is", transcription: "[из]", translate: "есть, является"},
  {word: "isn't", transcription: "[изнт]", translate: "не является"},
  {word: "it", transcription: "[ит]", translate: "это, он, она"},
  {word: "it's", transcription: "[итс]", translate: "это, это есть"},
  {word: "its", transcription: "[итс]", translate: "его, ее"},
  {word: "jacket", transcription: "[джакит]", translate: "куртка"},
  {word: "jeans", transcription: "[джинс]", translate: "джинсы"},
  {word: "jerk", transcription: "[джёрк]", translate: "придурок, толчок"},
  {word: "job", transcription: "[джоб]", translate: "работа"},
  {word: "join", transcription: "[джойн]", translate: "присоединяться"},
  {word: "joke", transcription: "[джоук]", translate: "шутка"},
  {word: "jump", transcription: "[джамп]", translate: "прыгать"},
  {word: "just", transcription: "[джаст]", translate: "просто, только что"},
  {word: "keep", transcription: "[кип]", translate: "держать, сохранять"},
  {word: "kept", transcription: "[кепт]", translate: "держал, сохранял"},
  {word: "key", transcription: "[ки]", translate: "ключ"},
  {word: "kick", transcription: "[кик]", translate: "ударять ногой"},
  {word: "kid", transcription: "[кид]", translate: "ребенок"},
  {word: "kill", transcription: "[кил]", translate: "убивать"},
  {word: "kind", transcription: "[кайнд]", translate: "добрый, вид"},
  {word: "kiss", transcription: "[кис]", translate: "целовать"},
  {word: "kitchen", transcription: "[китчен]", translate: "кухня"},
  {word: "knee", transcription: "[ни]", translate: "колено"},
  {word: "knew", transcription: "[нью]", translate: "знал"},
  {word: "knock", transcription: "[нок]", translate: "стучать"},
  {word: "know", transcription: "[ноу]", translate: "знать"},
  {word: "known", transcription: "[ноун]", translate: "известный"},
  {word: "lady", transcription: "[лейди]", translate: "леди, дама"},
  {word: "land", transcription: "[лэнд]", translate: "земля"},
  {word: "large", transcription: "[лардж]", translate: "большой"},
  {word: "last", transcription: "[ласт]", translate: "последний"},
  {word: "late", transcription: "[лейт]", translate: "поздний"},
  {word: "laugh", transcription: "[лаф]", translate: "смех, смеяться"},
  {word: "lay", transcription: "[лей]", translate: "лежать"},
  {word: "lead", transcription: "[лид]", translate: "вести"},
  {word: "lean", transcription: "[лин]", translate: "наклоняться"},
  {word: "learn", transcription: "[лён]", translate: "учиться, узнавать"},
  {word: "least", transcription: "[лист]", translate: "наименьший, по крайней мере"},
  {word: "leave", transcription: "[лив]", translate: "оставлять, уходить"},
  {word: "led", transcription: "[лед]", translate: "вел, руководил"},
  {word: "left", transcription: "[лефт]", translate: "оставил, ушел"},
  {word: "leg", transcription: "[лег]", translate: "нога"},
  {word: "less", transcription: "[лесс]", translate: "менее"},
  {word: "let", transcription: "[лет]", translate: "позволять"},
  {word: "letter", transcription: "[леттер]", translate: "письмо"},
  {word: "lie", transcription: "[лай]", translate: "лгать, ложь"},
  {word: "life", transcription: "[лаиф]", translate: "жизнь"},
  {word: "lift", transcription: "[лифт]", translate: "поднимать"},
  {word: "light", transcription: "[лайт]", translate: "свет, светлый"},
  {word: "like", transcription: "[лайк]", translate: "как, как будто"},
  {word: "line", transcription: "[лайн]", translate: "линия, строка"},
  {word: "lip", transcription: "[лип]", translate: "губа"},
  {word: "listen", transcription: "[лисн]", translate: "слушать"},
  {word: "little", transcription: "[литл]", translate: "маленький, немного"},
  {word: "live", transcription: "[лив]", translate: "жить"},
  {word: "lock", transcription: "[лок]", translate: "замок, запирать"},
  {word: "locker", transcription: "[локер]", translate: "ящик, шкафчик"},
  {word: "long", transcription: "[лонг]", translate: "длинный, долгий"},
  {word: "look", transcription: "[лук]", translate: "смотреть, взгляд"},
  {word: "lose", transcription: "[луз]", translate: "терять"},
  {word: "lost", transcription: "[лост]", translate: "потерянный"},
  {word: "lot", transcription: "[лот]", translate: "много"},
  {word: "loud", transcription: "[лауд]", translate: "громкий"},
  {word: "love", transcription: "[лав]", translate: "любовь, любить"},
  {word: "low", transcription: "[лоу]", translate: "низкий"},
  {word: "lunch", transcription: "[ланч]", translate: "ланч, обед"},
  {word: "mad", transcription: "[мэд]", translate: "безумный, злой"},
  {word: "made", transcription: "[мейд]", translate: "сделанный, сделал"},
  {word: "make", transcription: "[мейк]", translate: "делать"},
  {word: "man", transcription: "[мэн]", translate: "человек, мужчина"},
  {word: "manage", transcription: "[мэнэдж]", translate: "управлять, справляться"},
  {word: "many", transcription: "[мэни]", translate: "много"},
  {word: "mark", transcription: "[марк]", translate: "метка, отметка"},
  {word: "marry", transcription: "[мэри]", translate: "жениться, выходить замуж"},
  {word: "match", transcription: "[мэтч]", translate: "матч, соответствовать"},
  {word: "matter", transcription: "[мэтэр]", translate: "дело, вопрос, иметь значение"},
  {word: "may", transcription: "[мэй]", translate: "мочь, возможно"},
  {word: "maybe", transcription: "[мэйби]", translate: "возможно, может быть"},
  {word: "me", transcription: "[ми]", translate: "меня, мне"},
  {word: "mean", transcription: "[мин]", translate: "означать, иметь в виду"},
  {word: "meant", transcription: "[мент]", translate: "подразумевал, имел в виду"},
  {word: "meet", transcription: "[мит]", translate: "встречать"},
  {word: "memory", transcription: "[мемори]", translate: "память"},
  {word: "men", transcription: "[мен]", translate: "мужчины"},
  {word: "mention", transcription: "[ментшн]", translate: "упоминать"},
  {word: "met", transcription: "[мет]", translate: "встречал"},
  {word: "middle", transcription: "[мидл]", translate: "середина"},
  {word: "might", transcription: "[майт]", translate: "мог бы, возможно"},
  {word: "mind", transcription: "[майнд]", translate: "разум, ум"},
  {word: "mine", transcription: "[майн]", translate: "мой, шахта"},
  {word: "minute", transcription: "[минит]", translate: "минута"},
  {word: "mirror", transcription: "[миррор]", translate: "зеркало"},
  {word: "miss", transcription: "[мис]", translate: "скучать, пропустить"},
  {word: "mom", transcription: "[мам]", translate: "мама"},
  {word: "moment", transcription: "[момент]", translate: "момент"},
  {word: "money", transcription: "[мани]", translate: "деньги"},
  {word: "month", transcription: "[манс]", translate: "месяц"},
  {word: "mood", transcription: "[муд]", translate: "настроение"},
  {word: "more", transcription: "[мор]", translate: "больше"},
  {word: "morning", transcription: "[морнинг]", translate: "утро"},
  {word: "most", transcription: "[мост]", translate: "большинство, самый"},
  {word: "mother", transcription: "[мазер]", translate: "мать"},
  {word: "mouth", transcription: "[маут]", translate: "рот"},
  {word: "move", transcription: "[мув]", translate: "двигаться"},
  {word: "movie", transcription: "[муви]", translate: "фильм"},
  {word: "Mr.", transcription: "[мистер]", translate: "господин"},
  {word: "Mrs.", transcription: "[мисиз]", translate: "госпожа"},
  {word: "much", transcription: "[мач]", translate: "много"},
  {word: "mum", transcription: "[мам]", translate: "мама"},
  {word: "mumble", transcription: "[мамбл]", translate: "бормотать"},
  {word: "music", transcription: "[мьюзик]", translate: "музыка"},
  {word: "must", transcription: "[маст]", translate: "должен, обязан"},
  {word: "mutter", transcription: "[маттер]", translate: "бормотать, бурчать"},
  {word: "my", transcription: "[май]", translate: "мой"},
  {word: "myself", transcription: "[майселф]", translate: "себя, сам"},
  {word: "name", transcription: "[нейм]", translate: "имя"},
  {word: "near", transcription: "[ниэр]", translate: "близко"},
  {word: "nearly", transcription: "[ниэрли]", translate: "почти"},
  {word: "neck", transcription: "[нек]", translate: "шея, шею"},
  {word: "need", transcription: "[нид]", translate: "нуждаться, нужно"},
  {word: "nervous", transcription: "[нервас]", translate: "нервный"},
  {word: "never", transcription: "[невэр]", translate: "никогда"},
  {word: "new", transcription: "[нью]", translate: "новый"},
  {word: "next", transcription: "[некст]", translate: "следующий"},
  {word: "nice", transcription: "[найс]", translate: "хороший, приятный"},
  {word: "night", transcription: "[найт]", translate: "ночь"},
  {word: "no", transcription: "[но]", translate: "нет"},
  {word: "nod", transcription: "[нод]", translate: "кивок"},
  {word: "noise", transcription: "[нойз]", translate: "шум"},
  {word: "none", transcription: "[нан]", translate: "нет никакого"},
  {word: "normal", transcription: "[нормал]", translate: "нормальный"},
  {word: "nose", transcription: "[ноуз]", translate: "нос"},
  {word: "not", transcription: "[нот]", translate: "не"},
  {word: "note", transcription: "[нот]", translate: "заметка, нота"},
  {word: "nothing", transcription: "[назинг]", translate: "ничего"},
  {word: "notice", transcription: "[нотис]", translate: "замечать"},
  {word: "now", transcription: "[нау]", translate: "сейчас"},
  {word: "number", transcription: "[намбер]", translate: "номер"},
  {word: "obviously", transcription: "[обвиэсли]", translate: "очевидно"},
  {word: "of", transcription: "[ов]", translate: "из, от, о"},
  {word: "off", transcription: "[оф]", translate: "выключено"},
  {word: "offer", transcription: "[оффер]", translate: "предложение, предлагать"},
  {word: "office", transcription: "[офис]", translate: "офис"},
  {word: "often", transcription: "[офтэн]", translate: "часто"},
  {word: "oh", transcription: "[оу]", translate: "о, ах"},
  {word: "okay", transcription: "[окей]", translate: "хорошо, ладно"},
  {word: "old", transcription: "[олд]", translate: "старый"},
  {word: "on", transcription: "[он]", translate: "на, в"},
  {word: "once", transcription: "[ванс]", translate: "однажды"},
  {word: "one", transcription: "[ван]", translate: "один"},
  {word: "only", transcription: "[онли]", translate: "только"},
  {word: "onto", transcription: "[онтэу]", translate: "на, к"},
  {word: "open", transcription: "[оупэн]", translate: "открыть, открыто"},
  {word: "or", transcription: "[ор]", translate: "или"},
  {word: "order", transcription: "[ордэр]", translate: "порядок, заказ"},
  {word: "other", transcription: "[азер]", translate: "другой"},
  {word: "our", transcription: "[ауэр]", translate: "наш"},
  {word: "out", transcription: "[аут]", translate: "вне, из"},
  {word: "outside", transcription: "[аутсайд]", translate: "снаружи"},
  {word: "over", transcription: "[овэр]", translate: "над, сверх"},
  {word: "own", transcription: "[оун]", translate: "свой"},
  {word: "pack", transcription: "[пэк]", translate: "пачка, упаковывать"},
  {word: "pain", transcription: "[пэйн]", translate: "боль"},
  {word: "paint", transcription: "[пэйнт]", translate: "красить, краска"},
  {word: "pair", transcription: "[пэр]", translate: "пара"},
  {word: "pants", transcription: "[пэнтс]", translate: "брюки"},
  {word: "paper", transcription: "[пэйпэр]", translate: "бумага"},
  {word: "parents", transcription: "[пэрэнтс]", translate: "родители"},
  {word: "park", transcription: "[парк]", translate: "парк, парковать"},
  {word: "part", transcription: "[парт]", translate: "часть"},
  {word: "party", transcription: "[партй]", translate: "вечеринка"},
  {word: "pass", transcription: "[пэс]", translate: "проходить, пройти"},
  {word: "past", transcription: "[паст]", translate: "прошлое"},
  {word: "pause", transcription: "[поз]", translate: "пауза"},
  {word: "pay", transcription: "[пей]", translate: "платить"},
  {word: "people", transcription: "[пипл]", translate: "люди"},
  {word: "perfect", transcription: "[пёрфикт]", translate: "идеальный"},
  {word: "perhaps", transcription: "[пёрхэпс]", translate: "возможно"},
  {word: "person", transcription: "[пёрсн]", translate: "человек"},
  {word: "phone", transcription: "[фон]", translate: "телефон"},
  {word: "pick", transcription: "[пик]", translate: "выбирать, поднимать"},
  {word: "picture", transcription: "[пикчэр]", translate: "картина, фото"},
  {word: "piece", transcription: "[пис]", translate: "кусок"},
  {word: "pink", transcription: "[пинк]", translate: "розовый"},
  {word: "piss", transcription: "[пис]", translate: "писать"},
  {word: "place", transcription: "[плейс]", translate: "место"},
  {word: "plan", transcription: "[плэн]", translate: "план"},
  {word: "play", transcription: "[плей]", translate: "играть, игра"},
  {word: "please", transcription: "[плиз]", translate: "пожалуйста"},
  {word: "pocket", transcription: "[покет]", translate: "карман"},
  {word: "point", transcription: "[пойнт]", translate: "точка, указывать"},
  {word: "police", transcription: "[полис]", translate: "полиция"},
  {word: "pop", transcription: "[поп]", translate: "поп, взрыв"},
  {word: "position", transcription: "[пазишн]", translate: "позиция"},
  {word: "possible", transcription: "[поссибл]", translate: "возможный"},
  {word: "power", transcription: "[пауэр]", translate: "сила, мощь"},
  {word: "practically", transcription: "[практикали]", translate: "практически"},
  {word: "present", transcription: "[презент]", translate: "присутствующий, подарок"},
  {word: "press", transcription: "[пресс]", translate: "нажимать, пресса"},
  {word: "pretend", transcription: "[притэнд]", translate: "притворяться"},
  {word: "pretty", transcription: "[прити]", translate: "красивый"},
  {word: "probably", transcription: "[пробэбли]", translate: "возможно"},
  {word: "problem", transcription: "[проблэм]", translate: "проблема"},
  {word: "promise", transcription: "[промис]", translate: "обещание, обещать"},
  {word: "pull", transcription: "[пул]", translate: "тянуть, тащить"},
  {word: "punch", transcription: "[панч]", translate: "удар"},
  {word: "push", transcription: "[пуш]", translate: "толкать"},
  {word: "put", transcription: "[пут]", translate: "класть, ставить"},
  {word: "question", transcription: "[квэстчэн]", translate: "вопрос"},
  {word: "quick", transcription: "[квик]", translate: "быстрый"},
  {word: "quickly", transcription: "[квикли]", translate: "быстро"},
  {word: "quiet", transcription: "[квайет]", translate: "тихий"},
  {word: "quietly", transcription: "[квайетли]", translate: "тихо"},
  {word: "quite", transcription: "[квайт]", translate: "вполне"},
  {word: "race", transcription: "[рейс]", translate: "гонка, раса"},
  {word: "rain", transcription: "[рейн]", translate: "дождь"},
  {word: "raise", transcription: "[рейз]", translate: "поднимать"},
  {word: "ran", transcription: "[рэн]", translate: "бежал"},
  {word: "rang", transcription: "[рэнг]", translate: "звонил"},
  {word: "rather", transcription: "[рэзэр]", translate: "лучше, скорее"},
  {word: "reach", transcription: "[рич]", translate: "достигать"},
  {word: "read", transcription: "[рид]", translate: "читать"},
  {word: "ready", transcription: "[рэди]", translate: "готовый"},
  {word: "real", transcription: "[рил]", translate: "настоящий"},
  {word: "realize", transcription: "[рилаиз]", translate: "понимать"},
  {word: "really", transcription: "[рили]", translate: "действительно"},
  {word: "reason", transcription: "[ризэн]", translate: "причина, разум"},
  {word: "recognize", transcription: "[рекогнайз]", translate: "узнавать"},
  {word: "red", transcription: "[ред]", translate: "красный"},
  {word: "relationship", transcription: "[рилейшншип]", translate: "отношение"},
  {word: "relax", transcription: "[рилэкс]", translate: "расслабиться"},
  {word: "remain", transcription: "[римейн]", translate: "оставаться"},
  {word: "remember", transcription: "[римембэр]", translate: "помнить"},
  {word: "remind", transcription: "[римайнд]", translate: "напоминать"},
  {word: "repeat", transcription: "[рипит]", translate: "повторять"},
  {word: "reply", transcription: "[риплай]", translate: "ответ"},
  {word: "respond", transcription: "[риспонд]", translate: "отвечать"},
  {word: "rest", transcription: "[рест]", translate: "отдых"},
  {word: "return", transcription: "[ритёрн]", translate: "возвращение"},
  {word: "ride", transcription: "[райд]", translate: "езда, катание"},
  {word: "right", transcription: "[райт]", translate: "правильный, право"},
  {word: "ring", transcription: "[ринг]", translate: "кольцо, звонить"},
  {word: "road", transcription: "[роуд]", translate: "дорога"},
  {word: "rock", transcription: "[рок]", translate: "камень, качать"},
  {word: "roll", transcription: "[рол]", translate: "катиться, рулон"},
  {word: "room", transcription: "[рум]", translate: "комната"},
  {word: "rose", transcription: "[роуз]", translate: "роза"},
  {word: "round", transcription: "[раунд]", translate: "круглый, раунд"},
  {word: "rub", transcription: "[раб]", translate: "тереть"},
  {word: "run", transcription: "[ран]", translate: "бежать"},
  {word: "rush", transcription: "[раш]", translate: "спешить"},
  {word: "sad", transcription: "[сэд]", translate: "грустный"},
  {word: "safe", transcription: "[сейф]", translate: "безопасный"},
  {word: "said", transcription: "[сед]", translate: "сказал"},
  {word: "same", transcription: "[сейм]", translate: "тот же, такой же"},
  {word: "sat", transcription: "[сэт]", translate: "сидел"},
  {word: "save", transcription: "[сэйв]", translate: "спасать, сохранять"},
  {word: "saw", transcription: "[со]", translate: "пила, видел"},
  {word: "say", transcription: "[сэй]", translate: "говорить"},
  {word: "scare", transcription: "[скеэр]", translate: "пугать"},
  {word: "school", transcription: "[скул]", translate: "школа"},
  {word: "scream", transcription: "[скрийм]", translate: "кричать"},
  {word: "search", transcription: "[сёрч]", translate: "искать"},
  {word: "seat", transcription: "[сит]", translate: "место, сиденье"},
  {word: "second", transcription: "[сэкэнд]", translate: "второй, секунда"},
  {word: "see", transcription: "[си]", translate: "видеть"},
  {word: "seem", transcription: "[сим]", translate: "казаться"},
  {word: "seen", transcription: "[син]", translate: "виденный"},
  {word: "self", transcription: "[сэлф]", translate: "сам"},
  {word: "send", transcription: "[сенд]", translate: "отправлять"},
  {word: "sense", transcription: "[сенс]", translate: "чувство, смысл"},
  {word: "sent", transcription: "[сент]", translate: "отправил"},
  {word: "serious", transcription: "[сириас]", translate: "серьезный"},
  {word: "seriously", transcription: "[сириасли]", translate: "серьезно"},
  {word: "set", transcription: "[сет]", translate: "устанавливать, набор"},
  {word: "settle", transcription: "[сэтл]", translate: "улаживать"},
  {word: "seven", transcription: "[сэвэн]", translate: "семь"},
  {word: "several", transcription: "[сэвэрал]", translate: "несколько"},
  {word: "shadow", transcription: "[шэдоу]", translate: "тень"},
  {word: "shake", transcription: "[шейк]", translate: "трясти"},
  {word: "share", transcription: "[шээр]", translate: "делиться"},
  {word: "she", transcription: "[ши]", translate: "она"},
  {word: "she'd", transcription: "[шид]", translate: "она бы"},
  {word: "she's", transcription: "[шиз]", translate: "она есть"},
  {word: "shift", transcription: "[шифт]", translate: "смена"},
  {word: "shirt", transcription: "[шёрт]", translate: "рубашка"},
  {word: "shit", transcription: "[шит]", translate: "дерьмо, фекалии"},
  {word: "shock", transcription: "[шок]", translate: "шок"},
  {word: "shoe", transcription: "[шу]", translate: "туфля"},
  {word: "shook", transcription: "[шук]", translate: "тряс, трясся"},
  {word: "shop", transcription: "[шоп]", translate: "магазин"},
  {word: "short", transcription: "[шорт]", translate: "короткий"},
  {word: "shot", transcription: "[шот]", translate: "выстрел"},
  {word: "should", transcription: "[шуд]", translate: "должен"},
  {word: "shoulder", transcription: "[шоулдэр]", translate: "плечо"},
  {word: "shouldn't", transcription: "[шуднт]", translate: "не следует"},
  {word: "shout", transcription: "[шаут]", translate: "кричать"},
  {word: "shove", transcription: "[шав]", translate: "толкать"},
  {word: "show", transcription: "[шоу]", translate: "показывать, шоу"},
  {word: "shower", transcription: "[шауэр]", translate: "душ"},
  {word: "shrug", transcription: "[шраг]", translate: "пожимать плечами"},
  {word: "shut", transcription: "[шат]", translate: "закрыть"},
  {word: "sick", transcription: "[сик]", translate: "больной, тошнота"},
  {word: "side", transcription: "[сайд]", translate: "сторона"},
  {word: "sigh", transcription: "[сай]", translate: "вздох"},
  {word: "sight", transcription: "[сайт]", translate: "вид, зрение"},
  {word: "sign", transcription: "[сайн]", translate: "знак"},
  {word: "silence", transcription: "[сайлэнс]", translate: "молчание"},
  {word: "silent", transcription: "[сайлент]", translate: "тихий, молчаливый"},
  {word: "simply", transcription: "[симпли]", translate: "просто"},
  {word: "since", transcription: "[синс]", translate: "с тех пор, так как"},
  {word: "single", transcription: "[сингл]", translate: "один, холостой"},
  {word: "sir", transcription: "[сёр]", translate: "сэр"},
  {word: "sister", transcription: "[систэр]", translate: "сестра"},
  {word: "sit", transcription: "[сит]", translate: "сидеть"},
  {word: "situation", transcription: "[ситюэйшн]", translate: "ситуация"},
  {word: "six", transcription: "[сикс]", translate: "шесть"},
  {word: "skin", transcription: "[скин]", translate: "кожа"},
  {word: "sky", transcription: "[скай]", translate: "небо"},
  {word: "slam", transcription: "[слэм]", translate: "хлопнуть"},
  {word: "sleep", transcription: "[слип]", translate: "спать"},
  {word: "slightly", transcription: "[слайтли]", translate: "немного"},
  {word: "slip", transcription: "[слип]", translate: "скользить"},
  {word: "slow", transcription: "[слоу]", translate: "медленный"},
  {word: "slowly", transcription: "[слоули]", translate: "медленно"},
  {word: "small", transcription: "[смол]", translate: "маленький"},
  {word: "smell", transcription: "[смел]", translate: "запах"},
  {word: "smile", transcription: "[смайл]", translate: "улыбка"},
  {word: "smirk", transcription: "[смирк]", translate: "ухмылка"},
  {word: "smoke", transcription: "[смок]", translate: "курить, дым"},
  {word: "snap", transcription: "[снэп]", translate: "щелчок"},
  {word: "so", transcription: "[соу]", translate: "так, таким образом"},
  {word: "soft", transcription: "[софт]", translate: "мягкий"},
  {word: "softly", transcription: "[софтли]", translate: "мягко"},
  {word: "some", transcription: "[сам]", translate: "несколько"},
  {word: "somehow", transcription: "[самхау]", translate: "каким-то образом"},
  {word: "someone", transcription: "[самван]", translate: "кто-то"},
  {word: "something", transcription: "[самзин]", translate: "что-то"},
  {word: "sometimes", transcription: "[самтаймс]", translate: "иногда"},
  {word: "somewhere", transcription: "[самвэа]", translate: "где-то"},
  {word: "son", transcription: "[сан]", translate: "сын"},
  {word: "song", transcription: "[сонг]", translate: "песня"},
  {word: "soon", transcription: "[сун]", translate: "скоро"},
  {word: "sorry", transcription: "[сорри]", translate: "извини, сожалею"},
  {word: "sort", transcription: "[соут]", translate: "сорт, вид"},
  {word: "sound", transcription: "[саунд]", translate: "звук"},
  {word: "space", transcription: "[спейс]", translate: "пространство"},
  {word: "speak", transcription: "[спик]", translate: "говорить"},
  {word: "spend", transcription: "[спенд]", translate: "проводить (время)"},
  {word: "spent", transcription: "[спент]", translate: "провёл"},
  {word: "spoke", transcription: "[споук]", translate: "говорил"},
  {word: "spot", transcription: "[спот]", translate: "место"},
  {word: "stair", transcription: "[стэр]", translate: "лестница"},
  {word: "stand", transcription: "[стэнд]", translate: "стоять"},
  {word: "star", transcription: "[стар]", translate: "звезда"},
  {word: "stare", transcription: "[стэр]", translate: "пялиться, смотреть пристально"},
  {word: "start", transcription: "[старт]", translate: "начинать"},
  {word: "state", transcription: "[стэйт]", translate: "состояние, государство"},
  {word: "stay", transcription: "[стэй]", translate: "оставаться"},
  {word: "step", transcription: "[стэп]", translate: "шаг"},
  {word: "stick", transcription: "[стик]", translate: "палка, приклеивать"},
  {word: "still", transcription: "[стил]", translate: "все еще"},
  {word: "stomach", transcription: "[стамак]", translate: "живот, желудок"},
  {word: "stood", transcription: "[студ]", translate: "стоял"},
  {word: "stop", transcription: "[стоп]", translate: "останавливаться"},
  {word: "store", transcription: "[стор]", translate: "магазин"},
  {word: "story", transcription: "[стори]", translate: "рассказ, история"},
  {word: "straight", transcription: "[стрейт]", translate: "прямо, прямой"},
  {word: "strange", transcription: "[стрейндж]", translate: "странный"},
  {word: "street", transcription: "[стрит]", translate: "улица"},
  {word: "strong", transcription: "[стронг]", translate: "сильный"},
  {word: "struggle", transcription: "[страггл]", translate: "бороться, борьба"},
  {word: "stuck", transcription: "[стак]", translate: "застрял"},
  {word: "student", transcription: "[стюдент]", translate: "студент"},
  {word: "study", transcription: "[стади]", translate: "учиться, исследование"},
  {word: "stuff", transcription: "[стаф]", translate: "вещи, всякая фигня"},
  {word: "stupid", transcription: "[стюпид]", translate: "глупый"},
  {word: "such", transcription: "[сач]", translate: "такой, подобный"},
  {word: "suck", transcription: "[сак]", translate: "сосать, отстой"},
  {word: "sudden", transcription: "[садн]", translate: "внезапный"},
  {word: "suddenly", transcription: "[саднли]", translate: "внезапно"},
  {word: "suggest", transcription: "[саджест]", translate: "предлагать"},
  {word: "summer", transcription: "[саммер]", translate: "лето"},
  {word: "sun", transcription: "[сан]", translate: "солнце"},
  {word: "suppose", transcription: "[сапоуз]", translate: "полагать"},
  {word: "sure", transcription: "[шур]", translate: "уверенный"},
  {word: "surprise", transcription: "[сарпрайз]", translate: "сюрприз"},
  {word: "surround", transcription: "[сарраунд]", translate: "окружать"},
  {word: "sweet", transcription: "[свит]", translate: "сладкий"},
  {word: "table", transcription: "[тейбл]", translate: "стол"},
  {word: "take", transcription: "[тейк]", translate: "брать"},
  {word: "taken", transcription: "[тейкэн]", translate: "взятый"},
  {word: "talk", transcription: "[ток]", translate: "разговаривать"},
  {word: "tall", transcription: "[тол]", translate: "высокий"},
  {word: "teacher", transcription: "[тичэр]", translate: "учитель"},
  {word: "team", transcription: "[тим]", translate: "команда"},
  {word: "tear", transcription: "[тээр]", translate: "слеза"},
  {word: "teeth", transcription: "[тит]", translate: "зубы"},
  {word: "tell", transcription: "[тел]", translate: "говорить, рассказывать"},
  {word: "ten", transcription: "[тен]", translate: "десять"},
  {word: "than", transcription: "[дэн]", translate: "чем"},
  {word: "thank", transcription: "[сэнк]", translate: "благодарить"},
  {word: "that", transcription: "[дэт]", translate: "тот, что"},
  {word: "that's", transcription: "[дэтс]", translate: "это, что это"},
  {word: "the", transcription: "[зэ]", translate: "определенный артикль"},
  {word: "their", transcription: "[дэйр]", translate: "их"},
  {word: "them", transcription: "[дэм]", translate: "их, им"},
  {word: "themselves", transcription: "[демсельвз]", translate: "сами, себя"},
  {word: "then", transcription: "[ден]", translate: "тогда, потом"},
  {word: "there", transcription: "[дэр]", translate: "там"},
  {word: "there's", transcription: "[дэрз]", translate: "есть"},
  {word: "these", transcription: "[диз]", translate: "эти"},
  {word: "they", transcription: "[дэй]", translate: "они"},
  {word: "they'd", transcription: "[дэйд]", translate: "они бы"},
  {word: "they're", transcription: "[дэйр]", translate: "они есть"},
  {word: "thick", transcription: "[фик]", translate: "толстый"},
  {word: "thing", transcription: "[финг]", translate: "вещь"},
  {word: "think", transcription: "[финк]", translate: "думать"},
  {word: "third", transcription: "[зёрд]", translate: "третий"},
  {word: "this", transcription: "[дис]", translate: "этот"},
  {word: "those", transcription: "[доуз]", translate: "те"},
  {word: "though", transcription: "[доу]", translate: "хотя"},
  {word: "thought", transcription: "[фот]", translate: "мысль, думать"},
  {word: "three", transcription: "[фри]", translate: "три"},
  {word: "threw", transcription: "[фру]", translate: "бросил"},
  {word: "throat", transcription: "[фроут]", translate: "горло"},
  {word: "through", transcription: "[сру]", translate: "через"},
  {word: "throw", transcription: "[сроу]", translate: "бросить"},
  {word: "tie", transcription: "[тай]", translate: "завязывать"},
  {word: "tight", transcription: "[тайт]", translate: "плотный"},
  {word: "time", transcription: "[тайм]", translate: "время"},
  {word: "tiny", transcription: "[тайни]", translate: "крошечный"},
  {word: "tire", transcription: "[тайр]", translate: "уставать"},
  {word: "to", transcription: "[ту]", translate: "к"},
  {word: "today", transcription: "[тудэй]", translate: "сегодня"},
  {word: "together", transcription: "[тугезёр]", translate: "вместе"},
  {word: "told", transcription: "[толд]", translate: "сказал"},
  {word: "tomorrow", transcription: "[тамароу]", translate: "завтра"},
  {word: "tone", transcription: "[тон]", translate: "тон, оттенок"},
  {word: "tongue", transcription: "[танг]", translate: "язык"},
  {word: "tonight", transcription: "[тунайт]", translate: "сегодня вечером"},
  {word: "too", transcription: "[ту]", translate: "тоже, слишком"},
  {word: "took", transcription: "[тук]", translate: "взял"},
  {word: "top", transcription: "[топ]", translate: "верх, верхушка"},
  {word: "totally", transcription: "[тотэли]", translate: "полностью"},
  {word: "touch", transcription: "[тач]", translate: "касаться"},
  {word: "toward", transcription: "[товард]", translate: "к, в направлении"},
  {word: "town", transcription: "[таун]", translate: "город, городок"},
  {word: "track", transcription: "[трэк]", translate: "трек, след"},
  {word: "trail", transcription: "[трэйл]", translate: "след, тропа"},
  {word: "train", transcription: "[трейн]", translate: "поезд"},
  {word: "tree", transcription: "[три]", translate: "дерево"},
  {word: "trip", transcription: "[трип]", translate: "путешествие"},
  {word: "trouble", transcription: "[трабл]", translate: "проблема"},
  {word: "trust", transcription: "[траст]", translate: "доверие"},
  {word: "truth", transcription: "[трус]", translate: "правда"},
  {word: "try", transcription: "[трай]", translate: "пытаться"},
  {word: "turn", transcription: "[тёрн]", translate: "поворачивать, поворот"},
  {word: "TV", transcription: "[теви]", translate: "телевизор"},
  {word: "twenty", transcription: "[твенти]", translate: "двадцать"},
  {word: "two", transcription: "[ту]", translate: "два"},
  {word: "type", transcription: "[тайп]", translate: "тип, вводить текст"},
  {word: "uncle", transcription: "[анкл]", translate: "дядя"},
  {word: "under", transcription: "[андэр]", translate: "под"},
  {word: "understand", transcription: "[андэрстэнд]", translate: "понимать"},
  {word: "until", transcription: "[антэл]", translate: "до"},
  {word: "up", transcription: "[ап]", translate: "вверх"},
  {word: "upon", transcription: "[апон]", translate: "на, по"},
  {word: "us", transcription: "[ас]", translate: "нас, нам"},
  {word: "use", transcription: "[юз]", translate: "использовать"},
  {word: "usual", transcription: "[южуал]", translate: "обычный"},
  {word: "usually", transcription: "[южуэли]", translate: "обычно"},
  {word: "very", transcription: "[вери]", translate: "очень"},
  {word: "visit", transcription: "[визит]", translate: "посещать"},
  {word: "voice", transcription: "[войс]", translate: "голос"},
  {word: "wait", transcription: "[вэйт]", translate: "ждать"},
  {word: "wake", transcription: "[вэйк]", translate: "просыпаться"},
  {word: "walk", transcription: "[уок]", translate: "идти, гулять"},
  {word: "wall", transcription: "[уол]", translate: "стена"},
  {word: "want", transcription: "[вонт]", translate: "хотеть"},
  {word: "warm", transcription: "[уорм]", translate: "теплый"},
  {word: "warn", transcription: "[уорн]", translate: "предупреждать"},
  {word: "was", transcription: "[воз]", translate: "был"},
  {word: "wasn't", transcription: "[вознт]", translate: "не был"},
  {word: "watch", transcription: "[уоч]", translate: "смотреть, часы"},
  {word: "water", transcription: "[уотэр]", translate: "вода"},
  {word: "wave", transcription: "[вэйв]", translate: "волна"},
  {word: "way", transcription: "[вэй]", translate: "путь, способ"},
  {word: "we", transcription: "[ви]", translate: "мы"},
  {word: "we'll", transcription: "[вил]", translate: "мы будем"},
  {word: "we're", transcription: "[вир]", translate: "мы есть"},
  {word: "we've", transcription: "[вив]", translate: "у нас есть"},
  {word: "wear", transcription: "[уэр]", translate: "носить (одежду)"},
  {word: "week", transcription: "[вик]", translate: "неделя"},
  {word: "weird", transcription: "[виэрд]", translate: "странный"},
  {word: "well", transcription: "[вел]", translate: "хорошо"},
  {word: "went", transcription: "[вент]", translate: "пошел"},
  {word: "were", transcription: "[вёр]", translate: "были"},
  {word: "weren't", transcription: "[вёрнт]", translate: "не были"},
  {word: "wet", transcription: "[уэт]", translate: "мокрый"},
  {word: "what", transcription: "[вот]", translate: "что"},
  {word: "what's", transcription: "[вотс]", translate: "что это, что такое"},
  {word: "whatever", transcription: "[вотэвэр]", translate: "что угодно"},
  {word: "when", transcription: "[вен]", translate: "когда"},
  {word: "where", transcription: "[вэр]", translate: "где"},
  {word: "whether", transcription: "[везэр]", translate: "ли, либо"},
  {word: "which", transcription: "[вич]", translate: "который"},
  {word: "while", transcription: "[вайл]", translate: "в то время как"},
  {word: "whisper", transcription: "[уиспэр]", translate: "шептать"},
  {word: "white", transcription: "[уайт]", translate: "белый"},
  {word: "who", transcription: "[ху]", translate: "кто"},
  {word: "whole", transcription: "[хоул]", translate: "целый"},
  {word: "why", transcription: "[вай]", translate: "почему"},
  {word: "wide", transcription: "[вайд]", translate: "широкий"},
  {word: "wife", transcription: "[вайф]", translate: "жена"},
  {word: "will", transcription: "[вил]", translate: "буду, будешь, будет и т.д."},
  {word: "wind", transcription: "[уайнд]", translate: "ветер"},
  {word: "window", transcription: "[уиндоу]", translate: "окно"},
  {word: "wipe", transcription: "[уайп]", translate: "вытирать"},
  {word: "wish", transcription: "[уиш]", translate: "желать"},
  {word: "with", transcription: "[вид]", translate: "с, с помощью"},
  {word: "within", transcription: "[видин]", translate: "в пределах, внутри"},
  {word: "without", transcription: "[видаут]", translate: "без"},
  {word: "woke", transcription: "[воук]", translate: "пробудился, проснулся"},
  {word: "woman", transcription: "[уумэн]", translate: "женщина"},
  {word: "women", transcription: "[уимэн]", translate: "женщины"},
  {word: "won't", transcription: "[вонт]", translate: "не будет"},
  {word: "wonder", transcription: "[вандэр]", translate: "удивляться, чудо"},
  {word: "wood", transcription: "[ууд]", translate: "дерево"},
  {word: "word", transcription: "[уёрд]", translate: "слово"},
  {word: "wore", transcription: "[вор]", translate: "носил"},
  {word: "work", transcription: "[уёрк]", translate: "работа"},
  {word: "world", transcription: "[уёрлд]", translate: "мир"},
  {word: "worry", transcription: "[уори]", translate: "беспокоиться"},
  {word: "worse", transcription: "[вёрс]", translate: "хуже"},
  {word: "would", transcription: "[вуд]", translate: "бы"},
  {word: "wouldn't", transcription: "[вуднт]", translate: "не бы"},
  {word: "wow", transcription: "[вау]", translate: "ух ты"},
  {word: "wrap", transcription: "[рэп]", translate: "завертывать"},
  {word: "write", transcription: "[райт]", translate: "писать"},
  {word: "wrong", transcription: "[ронг]", translate: "неправильный"},
  {word: "yeah", transcription: "[йе]", translate: "да"},
  {word: "year", transcription: "[йир]", translate: "год"},
  {word: "yell", transcription: "[йел]", translate: "кричать"},
  {word: "yes", transcription: "[йес]", translate: "да"},
  {word: "yet", transcription: "[йет]", translate: "еще, уже"},
  {word: "you", transcription: "[ю]", translate: "ты, вы"},
  {word: "you'd", transcription: "[юд]", translate: "ты бы"},
  {word: "you'll", transcription: "[юл]", translate: "ты будешь"},
  {word: "you're", transcription: "[юр]", translate: "ты есть"},
  {word: "you've", transcription: "[юв]", translate: "у тебя есть"},
  {word: "young", transcription: "[янг]", translate: "молодой"},
  {word: "your", transcription: "[йор]", translate: "твой, ваш"},
  {word: "yourself", transcription: "[йорсэлф]", translate: "себя"}
]

words.each do |data|
  unless db[:words].where(word: data[:word]).any?
    db[:words].insert(
      word: data[:word],
      translation: data[:transcription],
      transcription: data[:translate]
    )
  end
end

puts "Seeded #{words.size} words."
